### ISSUE TITLE
Change black background color when cupertino modal fit opens.

### ISSUE THREAD

**Issue by westdabestdb** [jamesblasco/modal_bottom_sheet#10]
I'm using this with material scaffold and I wanted to achieve new ios style navigation. It works well except the background of my app is black. How do I change it ?

**Comment by bierbaumtim** [comment]
Background of your app means the scaffoldBackgroundColor is black ?

**Comment by westdabestdb** [comment]
Not really, you know the navigator background? Uh, like the black screen you see when you change navigation. I need to change that color.

**Comment by bierbaumtim** [comment]
Ah okay, I see. But I also have no idea how to change or if it is even possible.

**Comment by jamesblasco** [comment]
I think you mean the background marked as red no? 
Currently is not possible with this package but it is easy to implement.

<img height="321" alt="Captura de pantalla 2020-04-17 a las 20 54 11" src="https://user-images.githubusercontent.com/19904063/79604054-b75ab100-80ed-11ea-8f6f-c3fc65b8df4b.png">

**Comment by westdabestdb** [comment]
@jamesblasco Heck yes, that's what I need to do. Any help is appreciated!

**Comment by jamesblasco** [comment]
I can try to work on it this weekend or point you what you need to change.

 [Here](https://github.com/jamesblasco/modal_bottom_sheet/blob/481b23bf578878fe78d02e6fc7d7d3bfce0329f8/lib/src/bottom_sheets/cupertino_bottom_sheet.dart#L216) is where I define the black Color

**Comment by westdabestdb** [comment]
That's sweet! Yes, it's a good feature to have tbh.

**Comment by jamesblasco** [comment]
I added the new param `transitionBackgroundColor` that allows you to customize this param
