### ISSUE TITLE
Error: Getter not found: 'opaque'. assert(opaque)

### ISSUE THREAD

**Issue by MohsenHaydari** [jamesblasco/modal_bottom_sheet#102]
Error: Getter not found: 'opaque'. assert(opaque), ^^^^^^

affter update flutter sdk

error in new flutter sdk Flutter 1.24.0-6.0.pre • channel dev • https://github.com/flutter/flutter.git

and i removed this assert from your package and work fine, please fix this thanks

**Comment by jamesblasco** [comment]
This is solved in  1.0.1-dev
