### ISSUE TITLE
old code can not be run

### ISSUE THREAD

**Issue by jinfagang** [jamesblasco/modal_bottom_sheet#103]
It indicates I am not return widget, but it's actually widget...

![image](https://user-images.githubusercontent.com/21303438/97984952-78cede80-1e12-11eb-8bf5-c97eb97b133d.png)

**Comment by jamesblasco** [comment]
It is a breaking change inside the package. You should remove scrollController as param

**Comment by jinfagang** [comment]
@jamesblasco  Oh, thanks for you quick apply! Anything else need to change?Will this be consistent in the future?

**Comment by jamesblasco** [comment]
No, it is the only change. And the idea is to keep this change for future releases
You can see here what has changed for each version:
https://github.com/jamesblasco/modal_bottom_sheet/blob/master/CHANGELOG.md
