### ISSUE TITLE
Inside Navigation broken

### ISSUE THREAD

**Issue by welfvh** [jamesblasco/modal_bottom_sheet#104]
As you can replicate by opening the web demo and selecting 'Cupertino Modal with Inside Navigation', tapping a list item, touch 'touch here'; the navigation doesn't bring us back to the previous route, but instead to a blank page. Same in my implementation, don't know how to fix it.

**Comment by jamesblasco** [comment]
This should be fixed now! Thanks for submitting the issue :)
