### ISSUE TITLE
If place GoogleMap inside the modal, the map isn't scrolled vertically. 

### ISSUE THREAD

**Issue by kleyos** [jamesblasco/modal_bottom_sheet#110]
Hey, guys. The problem is in the title. Other directions work fine. 
The case with NestedScrollview doesn't fit either. cos the modal stop closing with swiping down. Is there a solution for my case?

**Comment by jamesblasco** [comment]
Could you share some of the code?

This looks like the modal drag is being prioritized to the maps drag. 

Try to use 
```dart
gestureRecognizers: Set()
    ..add(Factory<PanGestureRecognizer>(() => PanGestureRecognizer()))
```

As this is not a problem of the library I will close the issue, feel free to keep posting here and I will try to help

**Comment by jamesblasco** [comment]
If that does not work try
```dart
gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
          new Factory<OneSequenceGestureRecognizer>(
            () => new EagerGestureRecognizer(),
          ),
        ].toSet(),
```

**Comment by kleyos** [comment]
> ```dart
> new Factory<OneSequenceGestureRecognizer>(
>             () => new EagerGestureRecognizer(),
>           ),
> ```

Alright. I have a slightly difficult structure of my screen, which I want to show in the modal.  I'll try to show it. What do I want to achieve? this
<img width="260" alt="Screenshot 2020-11-13 at 11 51 05" src="https://user-images.githubusercontent.com/20066108/99059048-b23be280-25a6-11eb-8767-c0b6d2d44867.png">

mapWidget 
```
GoogleMap(
        gestureRecognizers: Set()
          ..add(
            fn.Factory<OneSequenceGestureRecognizer>(
              () => EagerGestureRecognizer(),
            ),
          ),
        markers: markers,
        zoomControlsEnabled: false,
        compassEnabled: false,
        myLocationButtonEnabled: false,
        myLocationEnabled: true,
        initialCameraPosition: CameraPosition(
          target: initialPosition,
          zoom: 15.0,
        ),
        onCameraMove: onCameraMove,
        onMapCreated: onMapCreated,
      );
```
Whole page 
```
Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: false,
        title: serchFieldWidget()
      ),
      body: PlacesNearbySheet(
            body: mapWidget()
          ),
```
**PlacesNearbySheet**  is the widget is used for the bottom slide panel
As you can see mapWidget has additional gestureRecognizers. but it has no effect on the vertical drag.

**Comment by kleyos** [comment]
and `gestureRecognizers: Set()
    ..add(Factory<PanGestureRecognizer>(() => PanGestureRecognizer()))` also doesn't work

**Comment by kleyos** [comment]
Guys. I found the solution. 
```
..add(
                            Factory<VerticalDragGestureRecognizer>(
                                () => VerticalDragGestureRecognizer()),
                          ),
```

And everything works now what I expect. Thank you for your help. 
lastly... I didn't find the example on github modal with a bar and modal with an avatar. Modal with bar file exists, but I can't see bar implementation into it.
