### ISSUE TITLE
Error: No named parameter with the name 'shadowThemeOnly

### ISSUE THREAD

**Issue by zsyphon** [jamesblasco/modal_bottom_sheet#111]
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-1.0.1-dev/lib/src/bottom_sheets/material_bottom_sheet.dart:42:32: Error: No named parameter with the name 'shadowThemeOnly'.
      theme: Theme.of(context, shadowThemeOnly: true),

[✓] Flutter (Channel master, 1.24.0-8.0.pre.260, on macOS 11.0.1 20B29 darwin-x64, locale en-US)
    • Flutter version 1.24.0-8.0.pre.260 at /Users/jchasecrafton/flutter
    • Framework revision 9b56241eef (83 minutes ago), 2020-11-16 14:47:04 -0600
    • Engine revision fae92ed574
    • Dart version 2.12.0 (build 2.12.0-46.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jchasecrafton/Library/Android/sdk
    • Platform android-29, build-tools 30.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • macOS 11.0.1 20B29 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198

**Comment by jamesblasco** [comment]
Please use the lastest released version 1.0.0. It is fixes there
