### ISSUE TITLE
Is there a way to await sheet comes back?

### ISSUE THREAD

**Issue by jinfagang** [jamesblasco/modal_bottom_sheet#114]
Wonder if there any way to await the showCupertinoBottomSheet comes back?

same as when we call Navigator.push .....

so that we can refresh local page after the next page done.

**Comment by jamesblasco** [comment]
. The function returns the same Future as Navigator.push

Do await showCupertino....

**Comment by jinfagang** [comment]
@jamesblasco But.... I await and do refresh, it actually doesn't refresh....

**Comment by jamesblasco** [comment]
Share some code then, but this is the implementation
https://github.com/jamesblasco/modal_bottom_sheet/blob/e26131c8096fa9ae91d26b873e208513be8f87a5/lib/src/bottom_sheets/cupertino_bottom_sheet.dart#L103-L130
