### ISSUE TITLE
shadowThemeOnly added to theme.of

### ISSUE THREAD

**Issue by troy191990** [jamesblasco/modal_bottom_sheet#117]
C:/flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-1.0.1-dev/lib/src/bottom_sheets/material_bottom_sheet.dart:42:32: Error: No named parameter with the name 'shadowThemeOnly'.
      theme: Theme.of(context, shadowThemeOnly: true),

I get this error when using a plugin which makes reference to this library.

When I comment out this library, the error goes away, however the popup no longer works, as it requires the method "showMaterialModalBottomSheet".

I think adding this param is the issue: shadowThemeOnly: true
![broken_library](https://user-images.githubusercontent.com/19688897/99886120-c5a01b00-2c42-11eb-9183-6b1d95705626.png)

**Comment by aguilaair** [comment]
See #109 you should be able to update the dependency manually to 1.0.0+1

**Comment by joniaiuser** [comment]
I think this error is back in the latest dev preview.

**Comment by jamesblasco** [comment]
Use the latest release version 1.0.0+1. The dev version is older(sorry about the wrong versioning).
