### ISSUE TITLE
modal_top_sheet ?

### ISSUE THREAD

**Issue by noordawod** [jamesblasco/modal_bottom_sheet#118]
Hi again.

I wonder, how hard it would be to declare an `enum ModalSheetPosition { top, bottom }` and allow consumers to decide where the modal should show itself? There are many use cases where a top modal sheet makes a lot of sense.

If I would like to contribute such a pr, and you agree that it can be useful, could you point me to the right files/classes/methods to focus on?

**Comment by jamesblasco** [comment]
I am not sure there are enough use cases to change all the page logic to support two directions.

Could you point me to some examples this is useful? 

I only see the case of an inside notification that you can dismiss. But something like this could be more easily implemented without dealing with scroll.

**Comment by noordawod** [comment]
Right on. Alright then, thank you for your feedback.
