### ISSUE TITLE
No background color not working

### ISSUE THREAD

**Issue by steve-cahn** [jamesblasco/modal_bottom_sheet#119]
When I apply a background color of transparent, I get a light opaque grey.
How can I have no backgroundColor on a showCupertinoModalBottomSheet?

I tried giving an elevation of 0, but it's still not working

**Comment by jamesblasco** [comment]
It is the shadow probably. I don’t think there is a direct way to remove it now, but you could easily extent CupertinoModalBottomSheetRoute and remove it.

I am working on big internal changes for the packages and I am afraid I can’t work on this now. Feel free to make a PR if you want 🙂

**Comment by GoodReese** [comment]
Could you please tell me how to use the shadow property ? I set it to BoxShadow(color: Colors.white), but still has grey blur effect , why ?
<img width="403" alt="image" src="https://user-images.githubusercontent.com/93602754/153971167-903812cc-66a2-4ca9-b1b1-6bf9ccb47818.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/93602754/153971248-4ad612cb-71fa-4f40-8ec0-b8cb688664a7.png">

**Comment by GoodReese** [comment]
I need to keep my CupertinoSliverNavigationBar with transparent color , so I try to figure out how to remove this shadow effect, please help me , thank you .
