### ISSUE TITLE
bloc provider with Cupertino Modal

### ISSUE THREAD

**Issue by osama188** [jamesblasco/modal_bottom_sheet#123]
I'm trying to use bloc provider to provide bloc to inner child with showCupertinoModalBottomSheet but the child can't read it.
Is it possible to provide bloc to child while using showCupertinoModalBottomSheet?

**Comment by jamesblasco** [comment]
Consider CupertinoModal as another route. When you use Navigator.of(context).push(). 
So you need to add the bloc provider before the Navigator/MaterialApp
