### ISSUE TITLE
Feature to disable drag when using CupertinoPageScaffold

### ISSUE THREAD

**Issue by hbali** [jamesblasco/modal_bottom_sheet#127]
If I'm using `CupertinoPageScaffold` the same rules apply as for the parent. Meaning I can't individually disable dragging on the `CupertinoPageScaffold`.

On iOS (check the calendar app) these pages cannot be dismissed by dragging. They have a slight bounce animation but are not dismissed. 

Is it possible to achive the same behaviour somehow? I have checked the source code but `CupertinoPageScaffold` seems to be deeply integrated with its parent animation and control.

**Comment by jamesblasco** [comment]
Yess you can prevent closing a modal by adding WillPop widget in your widget tree. This will bounce back the modal to the top if will pop returns false. Check the example with 'WillPopScope' inside this library
https://jamesblasco.github.io/modal_bottom_sheet/#/
