### ISSUE TITLE
Return-Value on Drag

### ISSUE THREAD

**Issue by attex** [jamesblasco/modal_bottom_sheet#128]
I could not find it in the documentation, but is there a way to pass some data when the BottomSheet is closed by dragging it down. 

Like i got it covered when my user taps on the Close-Icon. 

`IconButton
                    onPressed: () {
                      Navigator.pop(context, data);
                    },
                    icon: Icon(
                          Icons.close,
                          color: Colors.white,
                          size: 15,
                        ))`

Thanks in advance

**Comment by jamesblasco** [comment]
It is not possible to know that right now.  I will consider this part of https://github.com/jamesblasco/modal_bottom_sheet/issues/132
