### ISSUE TITLE
Disable background shrink

### ISSUE THREAD

**Issue by colehorvitz** [jamesblasco/modal_bottom_sheet#131]
Is there a way to disable the shrinkage of background widgets when a modal sheet is open? If not this would be a highly desirable feature.

**Comment by Zabadam** [comment]
When I use showMaterialModalBottomSheet() I get no background shrinkage. Is that a feature available only to one of the styles of ModalBottomSheet, like the iOS 13 Cupertino one?

**Comment by jamesblasco** [comment]
The shirk it is only available for the Cupertino modal as following the Human Design Guidelines from Apple.  

So if you want it you should use showCupertinoModalBottomSheet or create your own. 

If you don’t want it, you should use another one.

Officially there is no an option in the Apple Human Design Guidelines to disable the shrink, so I don’t plan to add this feature either

**Comment by colehorvitz** [comment]
Makes sense, thanks for the explanation!
