### ISSUE TITLE
Quick swipe down doesn't always dismiss the modal

### ISSUE THREAD

**Issue by subhash279** [jamesblasco/modal_bottom_sheet#134]
Hi,
First of all great work on the plugin. 

Sometimes a quick swipe down doesn't dismiss the plugin. We have to swipe it a long way down before it gets dismissed. I even tried setting "closeProgressThreshold" to 0.8 or higher but it doesn't seem to work. Even though only 60% of modal is visible, when I release it, it goes back to top. Since it is < 0.8, I assumed it should close. Or is my understanding of closeProgressThreshold wrong. 
Thanks!

**Comment by subhash279** [comment]
On a closer look, it just looks like `closeProgressThreshold` is not being passed into `ModalBottomSheet(` in bottom_sheet_route.dart page. Doing this fixes the issue. Can this small change be done on master branch pls.

**Comment by reesz** [comment]
@subhash279 did you add it to line 354? Currently trying to do this fix myself for now but adding this to the CupertinoModalBottomSheetRoute on 354, doesn't do anything for me?

**Comment by subhash279** [comment]
@reesz yeah it worked for me when I made the change locally.

**Comment by jamesblasco** [comment]
This should be fixed already in the null-safety preview package
