### ISSUE TITLE
Parameter `double closeProgressThreshold` for ModalBottomSheetRoute() is ignored/not forwarded to ModalBottomSheet

### ISSUE THREAD

**Issue by Zabadam** [jamesblasco/modal_bottom_sheet#140]
```
return ModalBottomSheetRoute(
// File a bug @ https://github.com/jamesblasco/modal_bottom_sheet/issues/new as param `closeProgressThreshold` is not forwarded
    closeProgressThreshold: 0.5,
    expanded: true,
    bounce: true,
    duration: const Duration(milliseconds: 300),
    animationCurve: Curves.easeInOutCirc,
    builder: (context) => ItemView(args.item),
);
```

closeProgressThreshold when passed here in my routes: of main() seems to have no effect on the resulting ModalBottomSheet.

Upon inspection, ModalBottomSheetRoute<T> does indeed pass closeProgressThreshold to _ModalBottomSheet<T>,  but here the parameter is lost.

bottom_sheet_route.dart @ Line 95, no pass of closeProgressThreshold to non-private ModalBottomSheet.

**Comment by jamesblasco** [comment]
This should be fixed already in the null-safety preview package
