### ISSUE TITLE
UI elements within Modal not rebuilding when state is changed

### ISSUE THREAD

**Issue by ayaanpathan** [jamesblasco/modal_bottom_sheet#142]
I'm trying to build a checkbox list and want to update the UI after checking/unchecking the checkbox. However, the UI does not update after changing the state of the checkbox. Can anyone help me with this?  Below is my code:

` showCupertinoModalBottomSheet(
                          context: context,
                          builder: (context) => Scaffold(
                            backgroundColor: Colors.white,
                            appBar: AppBar(
                              actions: [
                                TextButton(
                                  onPressed: () {
                                    Navigator.of(context).pop();
                                  },
                                  child: Text(
                                    'Clear All',
                                    style: kSubtitleBlueStyle,
                                  ),
                                )
                              ],
                              backgroundColor: Colors.white,
                              iconTheme: IconThemeData(color: Colors.black),
                              elevation: 0,
                              title: Text(
                                'Filters',
                                style: kSubtitleStyle,
                              ),
                              // leading: Padding(
                              //   padding: const EdgeInsets.symmetric(horizontal: 25.0, vertical: 25),
                              //   child: Text(
                              //     'Filters',
                              //     style: kSubtitleStyle,
                              //   ),
                              // ),
                              automaticallyImplyLeading: false,
                            ),
                            body: Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                                children: <Widget>[
                                  Container(
                                    width: MediaQuery.of(context).size.width * 0.5,
                                    color: systemWideGreyColor,
                                    height: MediaQuery.of(context).size.height,
                                    child: ListView.builder(
                                        itemCount: 1, // the length
                                        shrinkWrap: true,
                                        itemBuilder: (context, index) {
                                          return Container(
                                            color: Colors.white,
                                            child: SingleChildScrollView(
                                                child: Column(
                                                  mainAxisSize: MainAxisSize.min,
                                                  children: new List.generate(
                                                    1,
                                                        (index) => new ListTile(
                                                      title: Text('Categories'),
                                                    ),
                                                  ),
                                                )),
                                          );
                                        }),
                                  ),
                                  Container(
                                    width: MediaQuery.of(context).size.width * 0.5,
                                    // height: MediaQuery.of(context).size.height,
                                    child: Column(
                                      children: <Widget>[
                                        ListView.builder(
                                          shrinkWrap: true,
                                          padding: const EdgeInsets.all(8.0),
                                          itemCount: lovCountryServices.length,
                                          itemBuilder: (BuildContext context, int index) {
                                            var item = lovCountryServices[index];
                                            return CheckboxListTile(
                                              title: Text(item['name']),
                                              value: item['is_active'],
                                              onChanged: (val) {
                                                setState(() {
                                                  item['is_active'] = val;
                                                });
                                              },
                                            );
                                          },
                                        ),
                                        RaisedButton(
                                          onPressed: () => print("sending to backend"),
                                          child: Text("SEND"),
                                        )
                                      ],
                                    ),
                                  ),
                                ]),
                          ),
                        );`

**Comment by ItsRyanWu** [comment]
Use Flutter's StatefulBuilder to wrap ModalBottomSheet will work in your case.

**Comment by ItsRyanWu** [comment]
Use Flutter's StatefulBuilder to wrap ModalBottomSheet will work in your case.
