### ISSUE TITLE
Conditionally 'lock' modal

### ISSUE THREAD

**Issue by LEMUSADR000** [jamesblasco/modal_bottom_sheet#146]
Is there any way to at first allow for dismissal of modal, and once a condition is met remove that ability? I'm already doing this via button action but it would be cool if I could swipe to dismiss and then lock afterwards.

**Comment by jamesblasco** [comment]
You can prevent that a modal is dismissed by adding the widget `WillPopScope` as the example

https://github.com/jamesblasco/modal_bottom_sheet/blob/master/example/lib/modals/modal_will_scope.dart
