### ISSUE TITLE
Gesture Detector conflict with other packages

### ISSUE THREAD

**Issue by drosa88** [jamesblasco/modal_bottom_sheet#148]
Hi there 😊 I'm using your package for very long time and I love it! Now I found an issue or a limitation:

With your modal bottom sheet I open an image gallery (carousel). Inside this carousel the user can zoom on images with the package PhotoView. 

The problem is: Zooming is not working well if I don't disable the possibility to close the modal swiping to bottom. Seems that both gesture detectors are in conflict. 

In my case would be not a good usability to remove the gesture to close the modal. So I need another solution...

Is this a known behavior? Are there solutions? 

Thanks in advance for your feedback!

**Comment by drosa88** [comment]
I could solve it wrapping the Image Carousel with an `PhotoViewGestureDetectorScope`. So this topic can be closed :)

**Comment by jamesblasco** [comment]
Glad you manage to solve it yourself 💙
