### ISSUE TITLE
How to show modal sheet in stack with MaterialAPP home page?

### ISSUE THREAD

**Issue by jinfagang** [jamesblasco/modal_bottom_sheet#149]
Say, I have a MaterialAPP simply:

```dart

class MyApp extends StatelessWidget {


  @override
  Widget build(BuildContext context) {

    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: HomePage(),
        );
  }
}
```

And inside HomePage, is a simply Saffold, now I set a button in Scaffold's AppBar. I want click the button and showModalSheet in cupertino style, also, I want this HomePage be stacked behind it (like they stack nav multiple times).

I can set Route method since it's homepage already, doesn't Route. How do I make it stack in this scenario?

**Comment by jamesblasco** [comment]
Please, follow the guide to use `MaterialWithModalsPageRoute`
https://github.com/jamesblasco/modal_bottom_sheet#caution-to-animate-the-previous-route-some-changes-are-needed

**Comment by peterchibunna** [comment]
I have not been able to achieve the stack effect. Can anyone put up a guide?
