### ISSUE TITLE
How to programmaticaly dismiss the modal ?

### ISSUE THREAD

**Issue by Nendeurss** [jamesblasco/modal_bottom_sheet#150]
I am using Cubit and I want to auto dismiss the modal when the "Submit" button is clicked. Is there any way to do that ?

**Comment by DenDos** [comment]
@Nendeurss I assume you can just call  `Navigator.pop(context);` inside the "Submit" button function handler.

**Comment by jamesblasco** [comment]
Thanks, @DenDos  for providing the solution.
The modal is indeed a normal Route in the Navigator, so `Navigator.pop(context)`. If it does not close, check that you are not be using a context reference that does not contain the Navigator you use to push the view.
