### ISSUE TITLE
Scaling down of the previous page

### ISSUE THREAD

**Issue by plavunov** [jamesblasco/modal_bottom_sheet#151]
Hey, thanks for the fantastic package!

I'm successfully displaying a modal page like this: `   showCupertinoModalBottomSheet(
                          expand: false,
                          context: context,
                          backgroundColor: Colors.transparent,
                          builder: (context) =>
                              ItemFullView("Item")
                        )`

However, unlike the demo app, the previous page doesn't dim and scale down. Could you please tell me what are the *essential* steps/changes to the page widget to get this effect?

**Comment by jamesblasco** [comment]
Hello, please follow the guide to use `MaterialWithModalsPageRoute`
https://github.com/jamesblasco/modal_bottom_sheet#caution-to-animate-the-previous-route-some-changes-are-needed

**Comment by plavunov** [comment]
I am sorry but that doesn't help. No matter what I do from that page, the background is not scaling. Can you be more specific about the steps required to be done?

**Comment by jamesblasco** [comment]
Could you share some code on how are you doing it?

**Comment by plavunov** [comment]
I already did. This is a simple test app and I do not have anything else. What are the essential elements, like widgets that I need to specify in the root of MaterialApp?

**Comment by jamesblasco** [comment]
No, your previous routes need to be using the `MaterialWithModalsPageRoute`, that is it. Nothing else is required.

So you are probably using the MaterialApp home and routes params that use MaterialPageRoute by default. In the readme you have the steps to fix that for three different cases. 

I would need to see your MaterialApp to understand what you are doing with previous routes.

**Comment by chavesgu** [comment]
hey
If I use [getx](https://github.com/jonataslaw/getx) GetPage, how to do for this feature?

**Comment by Ben8557** [comment]
> hey If I use [getx](https://github.com/jonataslaw/getx) GetPage, how to do for this feature?

Did you find the answer?
