### ISSUE TITLE
Material modal goes over the app bar when the scrollable content is too long

### ISSUE THREAD

**Issue by prayatna** [jamesblasco/modal_bottom_sheet#154]
I am using the `showMaterialModalBottomSheet` that uses the `SingleChildScrollView` the child inside the widget is just a simple `Column `widget with long contents.
When I try opening the modal it shows up like this
![image](https://user-images.githubusercontent.com/4844401/114113397-0efeb780-9911-11eb-8b8c-2ec693aac1b9.png)
The modal should not be opening beyond the red marked area. 
How do I limit the height to show up like this 
![image](https://user-images.githubusercontent.com/4844401/114113612-ac59eb80-9911-11eb-9a4d-f058bef618c0.png)

**Comment by prayatna** [comment]
I'm on `modal_bottom_sheet: 1.0.0` as I'm still running on flutter 1.22.6

**Comment by jamesblasco** [comment]
Hello there, there is two ways you could do this.

First set the background color of the modal to transparent, add a SafeArea widget with top:true and rest to false and add a Material Widget inside were you add your background color

**Comment by jamesblasco** [comment]
Otherwise, you can use `showBarModalBottomSheet` with an SizedBox.shrink() widget in the control param.

**Comment by prayatna** [comment]
Thanks @jamesblasco, both ways worked for me but I ended up using the `showBarModalBottomSheet ` and adding `SizedBox.shirnk() `for the `topControl`. 

closing the issue now
cheers.
