### ISSUE TITLE
Interaction behind the bottom sheet

### ISSUE THREAD

**Issue by stepanzalis** [jamesblasco/modal_bottom_sheet#155]
Hi 👋 
I'm looking for a way how to enable user interaction behind the sheet when it's already shown. Example can be having a fullscreen map and a bottom sheet. I would like to enable interaction with map and have bottom sheet still visible. Can anyone could suggest the way how to approach it? 
BTW: Thanks for the package 💙

**Comment by jamesblasco** [comment]
Hello there. It is not possible. Right now the modal bottom sheet is a ModalRoute in Flutter. This is the description of a Modal Route https://api.flutter.dev/flutter/widgets/ModalRoute-class.html

> A route that blocks interaction with previous routes.

I am working to build a sheet that can be used inside any widget as you describe. But notice this is not the goal of this package and I will publish as a different one.

**Comment by stepanzalis** [comment]
Yeah, I should have done more research. Didn't know the difference between _modal_ and _ persistent_ bottom sheet. Thank you, closing this and looking forward to try the described new package in future.
