### ISSUE TITLE
Add the ability to interact with background page when isDismissable = false

### ISSUE THREAD

**Issue by brizaldi** [jamesblasco/modal_bottom_sheet#156]
Hi, currently when I set `isDismissable = false`, I cannot interact with the background page behind the modal. Is there a way to change that behavior?

The use case is, I want to make the modal dismissable only by pressing the button inside it or drag it down, while still maintain the ability to interact with the background page behind it.

**Comment by jamesblasco** [comment]
Duplicate https://github.com/jamesblasco/modal_bottom_sheet/issues/155
