### ISSUE TITLE
SingleChildScrollView inside BottomSheet is not scrollable

### ISSUE THREAD

**Issue by escamoteur** [jamesblasco/modal_bottom_sheet#165]
Hi,

I tried it with `enableDrag` true and false but in no case can I scroll an embedded SingleChildScrollView

Cheers
Thomas

**Comment by jamesblasco** [comment]
Hello there! Are you using ModalScrollController.of(context) as the scroll controller?

**Comment by escamoteur** [comment]
I don't use any scrollcontroller. do I have to do that?

**Comment by jamesblasco** [comment]
Scrollables inside modals should work as normal without anything extra needed to do. If you want to be able to close the modal while dragging/scrolling inside a scrollable area you have to use that scrollController provided by the modal. `controller: ModalScrollController.of(context)`.

**Comment by escamoteur** [comment]
I don't want to be able to close by dragging. Just that the SinglechildScrollView is scrollable

**Comment by escamoteur** [comment]
Seems it's it's everything fine. Seems you can no,longer scroll on Flutter Windows with by draging with the Mouse.
