### ISSUE TITLE
How to implement push replacement with the library.

### ISSUE THREAD

**Issue by fogfish** [jamesblasco/modal_bottom_sheet#168]
The built in navigation supports `pushReplacement`. How to achieve same effect with this library?

**Comment by jamesblasco** [comment]
Right now it is not possible to do this with the library. You could call 
`Navigator.of(context).pop();`
followed by a `showMaterialBottomSheet(context: someGlobalKeyInsideNavigator.context, ...)`;

**Comment by fogfish** [comment]
Thank you for the response! Indeed your proposal in a possible solution.
