### ISSUE TITLE
This package is not capable to manage state

### ISSUE THREAD

**Issue by kamleshwebtech** [jamesblasco/modal_bottom_sheet#176]
I am using this modal_bottom_sheet package to show bottom sheet but it does not able to manage/change state of self and parent area's state. I have uninstalled this package and used custom solution as;

```
showModalBottomSheet(
    context: context,
    builder: (context) {
      return StatefulBuilder(
          builder: (BuildContext context, StateSetter setState /*You can rename this!*/) {
        return Container(
          height: heightOfModalBottomSheet,
          child: RaisedButton(onPressed: () {
            setState(() {
              heightOfModalBottomSheet += 10;
            });
          }),
        );
      });
});
```

I struggled with your package for 4 hours then uninstalled it and used custom solution. Now every thing is working fine. Thanks.

**Comment by jamesblasco** [comment]
When using the showModalBottomSheet or any of the methods from this package, consider adding all your login inside a widget

showModalBottomSheet(builder: () => MyWidget());

As the widgets inside the builder function are in a different Route from the one you call the method.

So updating the widget where you call showModalBottomSheet won’t update anything related to the inside. 

As you say StatefulBuilder can be a solution, but I would suggest creating a StatefulWidget class would be the best
