### ISSUE TITLE
Initial load performance/jank on iOS Simulator

### ISSUE THREAD

**Issue by cpboyd** [jamesblasco/modal_bottom_sheet#186]
I've noticed some slightly perceptible initial load lag (and jank) that worsens with more complex layouts.

**N.B.** This only occurs after initial load, so you have to quit the app and restart. (e.g. if using `flutter run` or Debug, closing the session) Hot restarts appear to retain whatever cached values are needed.

A simple repro with the example is to replace the button with the `ComplexModal`:

```dart
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Scaffold(
        body: CupertinoPageScaffold(
          backgroundColor: Colors.white,
          navigationBar: CupertinoNavigationBar(
            transitionBetweenRoutes: false,
            middle: Text('iOS13 Modal Presentation'),
            trailing: GestureDetector(
              child: Icon(Icons.arrow_forward),
              onTap: () => showCupertinoModalBottomSheet(
                expand: true,
                context: context,
                backgroundColor: Colors.transparent,
                builder: (context) => ComplexModal(),
              ),
            ),
          ),
```

With this example, there's slightly perceptible jank (like a 1s delay)... I've seen worse with more graphically complex modals.

Is there any way to better optimize or pre-cache these animations in the background?

**Comment by cpboyd** [comment]
Another note: With this example, it appears that scrolling the list also helps alleviate the issue.

This isn't the case with another app of mine (with more jank -- possibly due to a lot of images and more complex UI), but maybe helps indicate what the underlying cause is.

**Comment by sanjade** [comment]
I think its related to Flutter: https://flutter.dev/docs/perf/rendering/shader. 

Also I wouldn't use this package. It seems abandoned.

**Comment by jamesblasco** [comment]
Hello! Sorry I have been super busy these last two months. 
From this week I will have more time. I will make sure to review all the issues people have been submitting :)

Indeed, I think most of this problem is related to the shader rendering, as it only happens the first time the modal is animated.

**Comment by cpboyd** [comment]
@sanjade @jamesblasco Thanks for the advice! I tried looking into jank, but didn't realize this was related to the shaders.
