### ISSUE TITLE
When using CupertinoScaffold the bottom navigation bar on android goes black

### ISSUE THREAD

**Issue by mark8044** [jamesblasco/modal_bottom_sheet#189]
Ive currently set the `systemNavigationBarColor` to white:

```
  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
    statusBarColor: Colors.transparent, // status bar color
    systemNavigationBarColor: Colors.white, // navigation bar color
  ));
```

But as soon as I wrap my pages with a `CupertinoScaffold`, which I need to do to get the bottom sheet to work (which it does wonderfully), then that bar becomes all black and nothing I do makes it go to white, or any color readily

**Comment by mark8044** [comment]
My mistake, I was using another package that interacted poorly with this one.  When I removed that package it started working just fine...

**Comment by virakyuthpk** [comment]
> 

Could you share which package?
