### ISSUE TITLE
run : example/lib/main.dart ///  there is a issue.

### ISSUE THREAD

**Issue by bilalkubilay-git** [jamesblasco/modal_bottom_sheet#19]
warning code : 
`error: The method 'forgetChild' is always abstract in the supertype. (abstract_super_member_reference at [example] lib/examples/sliver_container.dart:72)`

i cant run because of this problem and i cant use it another app also. 
i hope you can find a solution. i already tried and i lost in lines because Solution hide from me because of code is belong you.

**Comment by jamesblasco** [comment]
Can you show me your `flutter doctor`

**Comment by bilalkubilay-git** [comment]
`[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G103, locale tr-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.` 

NOTE : Xcode lastest version cant install in Mojave OS what i have and thats why i don't have it. I don't think that it doesn't effect this issue. 

Your advise solved problem . There is no problem as you said in the " modal_bottom_sheet " . Thank you for your quick return. It works really well , thanks for all.
