### ISSUE TITLE
PlatformNavBar's height cut on iOS

### ISSUE THREAD

**Issue by YankoSoulisimo** [jamesblasco/modal_bottom_sheet#198]
I have PlatformScaffold with PlatformAppBar. When opened as a modal bottom sheet on iOS, the PlatformAppBar's height gets always cut (default for Cupertino is 44 and with modal bottom sheet it appears to be about 30). 

Code used:

@override
  Widget build(BuildContext context) {
    final localizations = AppLocalizations.of(context)!;
    return PlatformScaffold(
      appBar: PlatformAppBar(
...

Presenting with:

showCupertinoModalBottomSheet(
      context: context,
      useRootNavigator: true,
      builder: (_) => child,
    );

Where child is the widget built above.

**Comment by jamesblasco** [comment]
Sorry not sure what you mean with PlatformAppBar y PlatformScaffold. Is it a third-party package?

**Comment by meowofficial** [comment]
I think it means that `CupertinoNavigationBar` height is small when building it within `ModalSheet` because of status bar absense.
