### ISSUE TITLE
[Question] Why the modal doesn't rebuild on theme change? 

### ISSUE THREAD

**Issue by ManuLpz4** [jamesblasco/modal_bottom_sheet#199]
Hey guys! How it's going? Hope you are doing well :)

Do you know why the modal doesn't rebuild on theme change? :(

Please and thank you

**Comment by jamesblasco** [comment]
Could you share some code snippet?

Probably you need to create a StatelessWidget that contains the widgets you pass to the showModalBottomSheet method as the builder in it is only called once.

**Comment by ManuLpz4** [comment]
@jamesblasco sorry, I mean that the Flutter "native" modal uses the ```Theme.of(context).bottomSheetTheme.backgroundColor``` but the modalBar doesn't and I need to use it cause I want to show a modalBar to select the themeMode. Am I clear? 

Thanks for answer! 💙
