### ISSUE TITLE
The named parameter 'duration' is not defined

### ISSUE THREAD

**Issue by vincentderidder** [jamesblasco/modal_bottom_sheet#20]
According to the docs, it should be possible to change the duration with the named paramater ' duration'. Yet, this parameter does not exists on showCupertinoModalBottomSheet.

![image](https://user-images.githubusercontent.com/10989299/82535945-f6927c80-9b47-11ea-9eaf-e75be087711d.png)

**Comment by jamesblasco** [comment]
Hello @vincentderidder, the version in master is not released yet in pub.dev. I will push it soon.

**Comment by vincentderidder** [comment]
@jamesblasco Perfect! Thank you for the quick reply!

**Comment by jamesblasco** [comment]
This should be released now
