### ISSUE TITLE
systemOverlayStyle changes

### ISSUE THREAD

**Issue by mtskf** [jamesblasco/modal_bottom_sheet#206]
When showCupertinoModalBottomSheet is triggered, SystemUiOverlayStyle turns to dark mode (white text), but it won't be back to light mode (black text) when the modal is closed.

![image](https://user-images.githubusercontent.com/315819/144527104-5f84980c-7a4b-46d5-98ef-f0a5450bf100.png)

![image](https://user-images.githubusercontent.com/315819/144527238-08f0c82c-9b3e-4fdd-b109-c2e4c9e4ff95.png)

![image](https://user-images.githubusercontent.com/315819/144527349-e7490566-e39a-4f99-b8a5-3bde4ff0f9f5.png)

**Comment by v7lin** [comment]
#207 fix this issue

**Comment by jamesblasco** [comment]
You can define a style for the previous screen via:

1. AppBar
```dart
 AppBar(
  systemOverlayStyle: SystemUiOverlayStyle(
    // Status bar color
    statusBarColor: Colors.red, 

    // Status bar brightness (optional)
    statusBarIconBrightness: Brightness.dark, // For Android (dark icons)
    statusBarBrightness: Brightness.light, // For iOS (dark icons)
  ),
)
```
2.  Or using an AnnotatedRegion widget:

AnnotatedRegion<SystemUiOverlayStyle>(
  // Use [SystemUiOverlayStyle.light] for white status bar 
  // or [SystemUiOverlayStyle.dark] for black status bar
  // https://stackoverflow.com/a/58132007/1321917
  value: SystemUiOverlayStyle.light,
  child: Scaffold(...),
);

The modal sets the SystemUiOverlayStyle.light when the modal region reaches the top, when it leaves the top it should go back to the previous one defined. But in your case there is no default defined
