### ISSUE TITLE
[Feature request] Set animation curve in constructor

### ISSUE THREAD

**Issue by emvaized** [jamesblasco/modal_bottom_sheet#21]
Currently to change the duration of opening animation I have to modify the source code of package (variable `_bottomSheetDuration` in `bottom_sheet_route.dart`), and I think there must be an easier way to do it. 
Also I didn't find a way to set `curve` at all.

**Comment by marklin2012** [comment]
I have the same problem: 

``` 
void presentModal(Widget page) {
    CupertinoScaffold.showCupertinoModalBottomSheet(
        animationCurve: Curves.elasticInOut,
        duration: const Duration(milliseconds: 3000),
        context: context,
        builder: (context, scrollController) => page);
  }
```

the `duration` works fine, but the `curve` doesn't work.

**Comment by jamesblasco** [comment]
Please, check [this comment ](https://github.com/jamesblasco/modal_bottom_sheet/issues/13#issuecomment-625175862).
Unfortunately, I lack the time to implement this until at least August.

**Comment by jamesblasco** [comment]
It should work now, and it has the material pre-defined curve as default now
