### ISSUE TITLE
Modal as a page opened using a route

### ISSUE THREAD

**Issue by czaku** [jamesblasco/modal_bottom_sheet#218]
Hi all,

As in the title, is it possible? I cannot find an example of how to do that. I am using GetX and would like to navigate to a route (with page, bindings, controller defined) but the route to open a modal rather than a page on the navigation stack.

Thanks,
Luke

**Comment by jamesblasco** [comment]
Hey! This route should be possible to be pushed the same as showModal, showDialog from the Flutter Frameworks. 

There is no support for GetX and there is no plan for it. Maybe someone can create another package that adds combines both packages together
