### ISSUE TITLE
How to use sheet with scaffold that has app bar and body that scrolls, but drag only works on the app bar

### ISSUE THREAD

**Issue by talmr-k** [jamesblasco/modal_bottom_sheet#219]
For example, with the ios sheet.

How can I have a Scaffold(appBar, body) inside the sheet, but have the drag to dismiss only work when dragging the app bar? Dragging the scrollable body only scrolls the ListView, and shouldn't dismiss the sheet. 

I've seen this behavior in the maps and other apps, wondering how to emulate this here.

**Comment by jamesblasco** [comment]
If you use a ListView it should as easy as removing the `ModalBottomController.of(context)` and setting primary to false:
```dart
ListView(
       primary: false,
```

**Comment by jamesblasco** [comment]
To block all the body and not just the ScrollView you can create a GestureDetector that blocks the one from the Sheet

```dart
Scaffold(
  appBar: ....,
  body:  GestureDetector(
        onVerticalDragUpdate: (details) {},
        onVerticalDragEnd: (details) {},
        child: MyContent()
   ),
),

**Comment by talmr-k** [comment]
@jamesblasco thanks so much! AWESOME
