### ISSUE TITLE
How to use a `CustomScrollView` inside of the `builder`

### ISSUE THREAD

**Issue by aytunch** [jamesblasco/modal_bottom_sheet#221]
I am using a package which manages its own `ScrollController` so I can not pass `ModalScrollController.of(context)` into it.
The package is [vertical_scrollable_tabview](https://github.com/wayne900204/vertical_scrollable_tabview)

Is there a way to use `ModalBottomSheet` and still be able to dismiss the sheet if the `CustomScrollView`s position is at the top?
When the content is smaller than the remaning height it works fine but when it is bigger, hence scrollable, the sheet does not dismiss and we see the overscroll effect.

This video might help.

https://user-images.githubusercontent.com/6442915/155860771-a93eef33-7d4c-4aef-8b6f-e47b4c827537.mov

**Comment by jamesblasco** [comment]
Sorry but there are no plans in the close future to support other ScrollControllers than the one provided by this framework.
It is required that this library controls the scroll controller so it can sync the user drag input for the scroll and the drag.

From my previous experience, there are ways to achieve that UI without requiring a custom ScrollController.
