### ISSUE TITLE
Error during project build using library modal_bottom_sheet: ^2.0.0

### ISSUE THREAD

**Issue by sanyakuznezov** [jamesblasco/modal_bottom_sheet#223]
I can't build the project due to an error:

flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-2.0.0/lib/src/bottom_sheet.dart:303:27: Error: Couldn't find constructor 'VelocityTracker'.
       _velocityTracker = VelocityTracker();

**Comment by jamesblasco** [comment]
This has been fixed now on version `modal_bottom_sheet: ^2.0.1`
