### ISSUE TITLE
How do I detect if the Modal Bottom Sheet is currently open

### ISSUE THREAD

**Issue by jahnli** [jamesblasco/modal_bottom_sheet#225]
How to check whether modal_bottom_sheet is currently open, and if so, then closed

**Comment by jamesblasco** [comment]
The sheet behaves like any other route in the flutter framework. 

You can detect when is closed in several ways, the simplest is to do:

bool isModalOpen = true;
await showCustomModalBottomSheet(...);
isModalOpen = false;
