### ISSUE TITLE
Unwanted onWillPop calls on newest 2.0.1 version

### ISSUE THREAD

**Issue by marcsanny** [jamesblasco/modal_bottom_sheet#229]
Let's imagine our `showCupertinoModalBottomSheet` looks something like this:
```
CupertinoScaffold.showCupertinoModalBottomSheet(
  expand: true,
  context: context,
  backgroundColor: Colors.transparent,
  builder: (context) => WillPopScope(
    onWillPop: onWillPop,
    child: YourContent(),
  ),
);
```

**Problem**: 
`onWillPop` from `WillPopScope` is called even if there was no actual `pop` from the modal.

**Potential reason**:
Probably removing the check `if (widget.shouldClose != null && hasReachedWillPopThreshold)` in this PR [here](https://github.com/jamesblasco/modal_bottom_sheet/commit/08c080f68e5b2a4e4a3e24fa73cd2ca9f4d085b7#diff-b9d268f4ccd4b2072f835dda837cb81853f22080d1d51268e94beeaa125e449dR235) is the reason of such behavior.

Please let me know if I could help by providing more info.

**Comment by ziqq** [comment]
Any news?

**Comment by ChiPhanTlm** [comment]
Same here, when drag the modal down but drag up immediate instead of dismiss it

**Comment by marcsanny** [comment]
Hey everyone, I opened a PR with a fix: https://github.com/jamesblasco/modal_bottom_sheet/pull/244.

Until it will be (hopefully 🤞) merged, you can use my fork: https://github.com/marcsanny/modal_bottom_sheet.git

**Comment by jamesblasco** [comment]
This should be fixed with the latest changes. Please let me know if is no the case

**Comment by marcsanny** [comment]
> This should be fixed with the latest changes. Please let me know if is no the case

Yes, confirming that it's fixed , thanks :)

**Comment by ziqq** [comment]
@jamesblasco yes i confirmed, it's work fine.
