### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by TingzhouJia** [jamesblasco/modal_bottom_sheet#23]
Hello I am facing questions when building the app, 
<img width="1206" alt="截屏2020-06-01 上午10 39 41" src="https://user-images.githubusercontent.com/44245347/83420357-86f87900-a3f4-11ea-9eb1-a9e3c6c9f525.png">
<img width="679" alt="截屏2020-06-01 上午10 40 07" src="https://user-images.githubusercontent.com/44245347/83420359-87910f80-a3f4-11ea-84d1-583263a904c9.png">
<img width="336" alt="截屏2020-06-01 上午10 40 38" src="https://user-images.githubusercontent.com/44245347/83420360-8829a600-a3f4-11ea-928c-0218dd58dbe0.png">

**Comment by jamesblasco** [comment]
Hello, the last version of this package needs the last version of Flutter 1.17. 
You can update Flutter with running `$ flutter upgrade`.

If you don't want to update you can use a previous version of this package: 0.1.5

**Comment by TingzhouJia** [comment]
Thank you very much.
