### ISSUE TITLE
 Looking up a deactivated widget's ancestor is unsafe. E/flutter (27100): At this point the state of the widget's element tree is no longer stable. E/flutter (27100): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

### ISSUE THREAD

**Issue by HugoPowerMex** [jamesblasco/modal_bottom_sheet#236]
Looking up a deactivated widget's ancestor is unsafe.
E/flutter (27100): At this point the state of the widget's element tree is no longer stable.
E/flutter (27100): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

**Comment by jamesblasco** [comment]
Please I need more details to understand the error you are retrieving
