### ISSUE TITLE
Border around body content has a flickering grey border

### ISSUE THREAD

**Issue by InFaMoUsZero** [jamesblasco/modal_bottom_sheet#240]
Hi, I'm getting a strange issue when opening the sheet, it's causing my "body" UI to have a flicker on all borders around the body. The body has no borders and are disabled, set to null and I've tried setting them explicitly to the same colour as the background or setting border.style = borderstyle.none and nothing works.

I have attached a video which illustrates the issues.

https://user-images.githubusercontent.com/4587382/167914622-ee99b1dd-a9f1-443c-b192-7362c0865c63.mp4

**Comment by apkuhar** [comment]
@InFaMoUsZero did you manage to solve this? I have the same issue.

**Comment by InFaMoUsZero** [comment]
> @InFaMoUsZero did you manage to solve this? I have the same issue.

Nope, it's still happening. Updated to 2.1.0 and it's still there.

**Comment by InFaMoUsZero** [comment]
Turned out the fix is to change the DEFAULT scaffold background color, the one which can only be changed from updating the theme settings on the app level class.

```js
CupertinoApp(
      color: Colors.transparent,
      theme: const CupertinoThemeData(
        // If you're using a black background, set to black
        // Otherwise set to the same background color you're using.
        scaffoldBackgroundColor: Colors.black,
      ),
   );
```
