### ISSUE TITLE
Doesn't work with CupertinoTabScaffold

### ISSUE THREAD

**Issue by traed** [jamesblasco/modal_bottom_sheet#249]
Using onGenerateRoute and MaterialWithModalsPageRoute, if the builder returns a CupertinoPageScaffold everything works as in the examples, but if it returns a CupertinoTabScaffold the background doesn't animate (shrink). If I wrap the CupertinoTabScaffold with a CupertinoScaffold and use CupertinoTabScaffold.showCupertinoModalBottomSheet the background shrinks but the modal is contained within the shrunken background instead.

**Comment by jamesblasco** [comment]
Could you share a snippet of the problem you are having so I can reproduce it?
