### ISSUE TITLE
Reduce Package Size:

### ISSUE THREAD

**Issue by Zfinix** [jamesblasco/modal_bottom_sheet#25]
Can you kindly work on reducing the package size: 
![image](https://user-images.githubusercontent.com/25801929/84761853-f5773280-afc1-11ea-84f7-2417801262b9.png)

**Comment by jamesblasco** [comment]
Sure I will reduce the quality of the images. This shouldn't affect the size of the app, as it will only compile the files needed from lib.

**Comment by Zfinix** [comment]
Yeah I understand the issue is with running  flutter pub get is currently a bit slow

**Comment by jamesblasco** [comment]
Okey, I will do that. :). Thanks for sharing it

**Comment by Zfinix** [comment]
Thanks too.

**Comment by bierbaumtim** [comment]
Maybe it is a good idea to upload the images and the gif to an extra repo or a other cloud space snd using networkimage.

**Comment by jamesblasco** [comment]
Yeah, I think I will upload it to another branch in the same repository. I would like to keep all open

**Comment by bierbaumtim** [comment]
Yeah great idea. Would be much better than an extra repo.

**Comment by jamesblasco** [comment]
Done!
