### ISSUE TITLE
when pushing on root navigator showCupertinoModalBottomSheet rebuilds

### ISSUE THREAD

**Issue by NikosTsesmelis** [jamesblasco/modal_bottom_sheet#258]
I use a custom navigator inside the modal. I insert a starting page to the navigator. When pushing a page from inside the said page to the root navigator the showCupertinoModalBottomSheet build method is called which recreates the navigator with only the initial page and i lose all the other pages that were previously open. 

Works fine on 2.0.1.
Not working on 2.1.0.

**Comment by LeGoffMael** [comment]
might be related to https://github.com/jamesblasco/modal_bottom_sheet/pull/253

**Comment by jamesblasco** [comment]
It should be fixed by the PR from @LeGoffMael
