### ISSUE TITLE
how to set animation when use MaterialWithModalsPageRoute

### ISSUE THREAD

**Issue by 826327700** [jamesblasco/modal_bottom_sheet#259]
```dart
Navigator.of(context).push(MaterialWithModalsPageRoute(builder: (context) => TestPage()));
```

That no transition animation when I use MaterialWithModalsPageRoute push a page. how to resolve this ?

**Comment by jamesblasco** [comment]
For the transition you should use showMaterialBottomSheet. `MaterialWithModalsPageRoute`is just a helper for animating the previous route when using showCupertinoBottomSheet
