### ISSUE TITLE
Modal package not found

### ISSUE THREAD

**Issue by adeolaex** [jamesblasco/modal_bottom_sheet#26]
It's not really an issue, but you used and imported this modal folder in your main.dart example.
Please where in flutter sdk is this folder located ?
![Screenshot 2020-06-17 at PM 8 18 14](https://user-images.githubusercontent.com/42682873/84934627-e387b380-b0d7-11ea-99cf-03b1ad0e4e07.png)

**Comment by bierbaumtim** [comment]
It is a folder inside the example app and not part of the flutter sdk.
If it is part of flutter or package the import starts with package:.

**Comment by adeolaex** [comment]
Okay! I just saw right now. Thank you very much.
