### ISSUE TITLE
Expose on popped API on showCupertinoModalBottomSheet

### ISSUE THREAD

**Issue by Amerr** [jamesblasco/modal_bottom_sheet#27]
I need to run a specific function when the modal sheet is closed or return some value, 
So is it possible to expose some API from `CupertinoModalBottomSheetRoute` which is rendered in   `showCupertinoModalBottomSheet`
```
await showCupertinoModalBottomSheet(
	context: context,
	builder: (context, scrollController) => Container();
	popped: () {
       print('Modal is closed')
	}
);
```

or 
the return value from widget which is rendered
```
T result = await showCupertinoModalBottomSheet<T>(
	context: context,
	builder: (context, scrollController) => Container();
);
```

**Comment by bierbaumtim** [comment]
A popped callback is not nessecary, because you can await the modal, as in your first proposal, and then call the methods you want.
Your second proposal already works. Since showCupertinoModalBottomSheet pushes a new route you can call ‘Navigator.of(context).pop(T);’ from inside the moral to return a value.

**Comment by Amerr** [comment]
@bierbaumtim  Thanks for your quick reply. 
Regarding the first proposal, I agree with what you said but the context of my question I need a trigger callback inside the Widget rendered in `showCupertinoModalBottomSheet ` so that it can pass some argument to its parent Widget.

Let's say `Widget A` renders `showCupertinoModalBottomSheet` which in turn renders `Widget B`. When the scroll gesture happens in closing the Modal Bottom sheet. I need the closing `Widget B` to pass some value to `Widget A`.

I hope it gives you a picture of my question.

**Comment by bierbaumtim** [comment]
Yeah, I understand the problem for the proposal. 
But having one question. Is the value passed from `Widget B` to `Widget A` always the same ? Because if it`s something like a user input in `Widget B`, a popped callback does not solve this problem, because you have no access to `Widget B` from the callback.

**Comment by jamesblasco** [comment]
You are right @Amerr, the ModalRoute should behave as other routes or models and allow to return a value from pop.
@bierbaumtim I didn't know about this before and I think it could be useful. This explains it very well https://flutter.dev/docs/cookbook/navigation/returning-data

**Comment by bierbaumtim** [comment]
Maybe I missed something but the cookbook does not explain the problem. It explains  how to pass data with Navigator.pop, what I mention in my first comment. 
But that does not solve the problem, when the modal gets closed through a scroll gesture. 

But a popped callback could possibly work, when we use a Key for `Widget B` and using that Key in the callback to get the data from the State of `Widget B`.

**Comment by jamesblasco** [comment]
True, I was not considering that problem


I think exposing the original pop return value  api should be enough for the most cases. When the modal is dismissed by a gesture usually means the user is canceling and then not data were introduced. 

For other cases, i would try to use WillPopScope Widget and a callback function, changenotifier valuer or any state management solution

**Comment by jamesblasco** [comment]
I am going to close this issue, as I think there are enough tools to solve this already.
If you want to do something after the modal is popped you can do it like that
```dart
await showCupertinoModalBottomSheet<T>(
	context: context,
	builder: (context, scrollController) => Container();
);
onModalClosed(); //Call a method after modal is closed
```
If you want to pass data when the modal is popped I would suggest one of the methods I said in my previous comment.

**Comment by attex** [comment]
@Amerr  could you solve this ?

I am currently facing the same problem and tried to user WillPopScope like so:

` WillPopScope(
        onWillPop: () async {
          List result = _getResult();
          Navigator.pop(context, result);
          return true;
        },
        child: Scaffold(`

But the result i get is null
