### ISSUE TITLE
how to get event when modal was closed ?

### ISSUE THREAD

**Issue by danielwalczak** [jamesblasco/modal_bottom_sheet#28]
I'm want to update state when modal is closed, but I don't know how to detect that. Any ideas ?

**Comment by jamesblasco** [comment]
The functions both showMaterialBottomModal or the cupertino one, returns a Future that it completes when the modal is closed.

So you can use add await show...BottomModal... 
and call setState after. This will be called when the modal closes

**Comment by danielwalczak** [comment]
Thanks for the info!

**Comment by kashifg4171** [comment]
> The functions both showMaterialBottomModal or the cupertino one, returns a Future that it completes when the modal is closed.
> 
> So you can use add await show...BottomModal...
> and call setState after. This will be called when the modal closes

hotreload is working but setstate is not working, by adding await before showMaterialModalBottomSheet
