### ISSUE TITLE
build error under flutter 3.5.0-8.0.pre.31 version

### ISSUE THREAD

**Issue by stoneLee81** [jamesblasco/modal_bottom_sheet#282]
Env: Channel master, 3.5.0-8.0.pre.31
build error 

../../../../.pub-cache/hosted/pub.flutter-io.cn/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:50:10:
Error: A value of type 'Object?' can't be returned from an async function with return type 'Future<T?>'.
 - 'Object' is from 'dart:core'.
 - 'Future' is from 'dart:async'.
  return result;

**Comment by kamami** [comment]
Same issue

**Comment by ardeshir-33033** [comment]
how did you fix this?
