### ISSUE TITLE
ModalBottomSheetRoute is imported from both

### ISSUE THREAD

**Issue by 1AhmedYasser** [jamesblasco/modal_bottom_sheet#284]
When I try to build and run the app I get this error:

`Error (Xcode): ../../.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet 2.1.0/lib/src/material_with_modal_page_route.dart:4:1: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.`

**Comment by declanwoods** [comment]
Happening on flutter `master`

**Comment by PavelSmertin** [comment]
i've got the same message after upgrade fluter to Flutter 3.5.0-10.0.pre.73 • channel master 

'Modal BottomSheet Route' is imported from both 'package:flutter/src/material/bottom sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.

**Comment by pom11** [comment]
same message for 2.1.2

```
Could not build the precompiled application for the device.
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/bar_bottom_sheet.dart:102:13: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
```

**Comment by glin94** [comment]
`../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:28:13: 
Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
      .push(ModalBottomSheetRoute<T>(`

**Comment by memmen** [comment]
Any update on a fix for this?

**Comment by xonaman** [comment]
Have your tried this?

```dart
import 'package:flutter/material.dart' hide ModalBottomSheetRoute;
import 'package:modal_bottom_sheet/modal_bottom_sheet';
```

**Comment by CoolDude53** [comment]
Had the same issue on flutter master, I made a fork that fixes it until this gets properly updated https://github.com/CoolDude53/modal_bottom_sheet

To import in your pubspec.yaml use:
```
modal_bottom_sheet:
    git:  
      url: https://github.com/CoolDude53/modal_bottom_sheet.git  
      path: modal_bottom_sheet
```

**Comment by rraayy** [comment]
Hi @CoolDude53 , 
Thanks so much, I think you need to add `ref: main` without the value, I will get the repsonse
'pub get failed (server unavailable) -- attempting retry '

below is OK.
`  modal_bottom_sheet:
    git:
     url: https://github.com/CoolDude53/modal_bottom_sheet.git
     ref: main
     path: modal_bottom_sheet`

**Comment by AlexDochioiu** [comment]
> Had the same issue on flutter master, I made a fork that fixes it until this gets properly updated https://github.com/CoolDude53/modal_bottom_sheet
> 
> To import in your pubspec.yaml use:
> 
> ```
> modal_bottom_sheet:
>     git:  
>       url: https://github.com/CoolDude53/modal_bottom_sheet.git  
>       path: modal_bottom_sheet
> ```

Was about to do the same, but you having done it already saved me a bit of time. Thanks!

P.S. for the ones wanting to be a bit more specific than just the branch, specify the actual commit so in case @CoolDude53 pushes more code, you don't get any unexpected changes.
```yaml
  modal_bottom_sheet:
    git:
      url: https://github.com/CoolDude53/modal_bottom_sheet.git
      ref: d3779be7d661481cc0d99090d6356a286ae4f86b
      path: modal_bottom_sheet
```

**Comment by jbankz** [comment]
check this issue #291 , i was able to resolve this problem using the following approach

**Comment by jamesblasco** [comment]
Please follow the migration guide I just created here https://github.com/jamesblasco/modal_bottom_sheet/issues/325

**Comment by sonaajayson** [comment]
hhgh
