### ISSUE TITLE
ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'

### ISSUE THREAD

**Issue by theappideasankit** [jamesblasco/modal_bottom_sheet#291]
../../../.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/material_with_modal_page_route.dart:4:1: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
import '../modal_bottom_sheet.dart';
^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:28:13: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:50:10: Error: A value of type 'Object?' can't be returned from an async function with return type 'Future<T?>'.
 - 'Object' is from 'dart:core'.
 - 'Future' is from 'dart:async'.
  return result;
         ^
../../../.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/bar_bottom_sheet.dart:102:13: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^
<img width="1429" alt="Screenshot 2022-11-07 at 1 32 37 AM" src="https://user-images.githubusercontent.com/97028121/200192345-7071aff7-4086-4076-986c-821ca8f9abdd.png">

../../../.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/bar_bottom_sheet.dart:125:10: Error: A value of type 'Object?' can't be returned from an async function with return type 'Future<T?>'.
 - 'Object' is from 'dart:core'.
 - 'Future' is from 'dart:async'.
  return result;
         ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/admin/Downloads/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1165

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/admin/Downloads/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s
Running Gradle task 'bundleRelease'...                             47.2s
Gradle task bundleRelease failed with exit code 1

**Comment by yogeshPutman** [comment]
We are also having similar issue even though we are not using the pacakage.
Error (Xcode): /Users/yogesh/.pub-cache/hosted/[pub.dev/modal_bottom_sheet-2.1.2/lib/src/material_with_modal_page_route.dart:5:1](http://pub.dev/modal_bottom_sheet-2.1.2/lib/src/material_with_modal_page_route.dart:5:1): Error:
'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and
'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.

**Comment by jbankz** [comment]
Same issue here

<img width="1108" alt="Screenshot 2022-11-14 at 11 25 54" src="https://user-images.githubusercontent.com/29983299/201636811-0fc89948-c7c0-4411-9344-011fa89955b2.png">

**Comment by jbankz** [comment]
> Same issue here, i am not even using the package
> 
> <img alt="Screenshot 2022-11-14 at 11 25 54" width="1108" src="https://user-images.githubusercontent.com/29983299/201636811-0fc89948-c7c0-4411-9344-011fa89955b2.png">

Prior to the above error, 
I noticed i wasn't using this package [https://pub.dev/packages/modal_bottom_sheet](url), but another package entire was dependent on it which in this case was this [https://pub.dev/packages/country_code_picker](url)

so what i did was to remove the package as it is been discontinued.

Then i ran the following commands and it worked.


`flutter clean`
`flutter pub get`

**Comment by theappideasankit** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/97028121/203010109-ffa6320c-011f-428b-8241-4b585fafeb67.png">


add this code your pubspec file

  modal_bottom_sheet:
    git:
      url: https://github.com/CoolDude53/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet

**Comment by PawelSzymanski89** [comment]
Tested, works fine, thanks!
