### ISSUE TITLE
Great on Phone, not so on Tablet

### ISSUE THREAD

**Issue by zgosalvez** [jamesblasco/modal_bottom_sheet#30]
This is an amazing package for use on the phone. However, it doesn't translate well on a tablet. Instead of animating the previous route, I just want to have a simpler sheet to show.

I tried setting `backgroundColor` to `Colors.black12` and the bottom sheet route to have padding, but the `boxShadow` is still visible. 

https://github.com/jamesblasco/modal_bottom_sheet/blob/b82a0c5393942b24a3f9ba2c6b09e0ec326e257e/lib/src/bottom_sheets/cupertino_bottom_sheet.dart#L46 

This is what I am trying to match:

![Form Sheet](https://miro.medium.com/max/1000/1*_wMQJDOyYpC94ekbfP-_JQ.png)
Reference: https://medium.com/@hacknicity/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e

**Comment by jamesblasco** [comment]
That one is the photo is not a ModalBottomSheet and it is considered a Dialog in Flutter. The modal bottom sheet is animated from the bottom while the dialog appears in the middle of the screen.

I would suggest you check the size of the device and use showCupertinoModalBottomSheet for phones and showDialog for tablets.

**Comment by zgosalvez** [comment]
Yes. I already implemented a device adaptive widget, which uses this package for phones, and a MaterialPageRoute for tablets. Using showDialog animates through fade so it doesn’t match the native iOS experience, since iOS modals animate from the bottom. You can see this on an iPad and going to Settings > Wi-Fi > Other...
I’ll try showFloatingBottomSheet tomorrow. Thanks for directing me to that possible solution.

**Comment by zgosalvez** [comment]
Looking good so far, except that my AppBar has a margin up top, so I set `primary` to `false` and the top padding is gone, but now has a bottom padding. How did you get this to work in `CupertinoScaffold.showCupertinoModalBottomSheet` without us having to modify our `AppBar`'s `primary`?

<img width="1280" alt="Screen Shot 2020-06-30 at 14 13 03" src="https://user-images.githubusercontent.com/1798166/86089974-d1484500-badb-11ea-9f1d-4d89c35dcc3d.png">

**Comment by jamesblasco** [comment]
The margin on top is probably the safe area padding, you can remove with
MediaQuery.removePadding(
            context: context,
            removeTop: true, //Remove top Safe Area
            child: child,
 ),
Before your scaffold and inside the modal.

**Comment by zgosalvez** [comment]
Success! Thanks for the quick assist. Hopefully, this helps other devs.
