### ISSUE TITLE
SheetController Animation stops, when state changes

### ISSUE THREAD

**Issue by kamami** [jamesblasco/modal_bottom_sheet#300]
I am using a BlocBuilder to build the content of my Sheet dynamically. Unfortunately the animation to scroll up is interrupted when the content changes. The animation starts by clicking a marker on the map, but it stops at random points. (It should animate to the very top edge of the screen btw.). Setting `primary: false` brings the expected behavior and the animation does not stop, but the sheet is not draggable anymore.

https://user-images.githubusercontent.com/43880037/205288241-fdc2e7de-d9de-49da-9538-0a1a12271da3.mov

```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:nonstop/bloc/selected_poi/selected_poi_bloc.dart';
import 'package:sheet/sheet.dart';

class Content extends StatelessWidget {
   Content({Key? key}) : super(key: key);
  final SheetController controller = SheetController();

  @override
  Widget build(BuildContext context) {
    return Sheet(
          minInteractionExtent: 20,
          backgroundColor: Theme.of(context).primaryColor,
          shape: const RoundedRectangleBorder(
              borderRadius: BorderRadius.vertical(top: Radius.circular(15))),
          maxExtent: MediaQuery.of(context).size.height,
          controller: controller,
          minExtent: 0,
          initialExtent: 0,
          child: BlocBuilder<SelectedPoiBloc, SelectedPoiState>(
        builder: (context, state) {
      if (state is SelectedPoiLoaded) {
        return ListView(
            primary: true,
            physics: const ClampingScrollPhysics(),
            children: [
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 100),
                child: Text(state.selectedPoi!.id),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 100),
                child: Text(state.selectedPoi!.id),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 100),
                child: Text(state.selectedPoi!.id),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 100),
                child: Text(state.selectedPoi!.id),
              ),
            ]);
      } else {
        return ListView(
            primary: true,
          children: []
        );
      }
    }));
  }
}
```

**Comment by maRci002** [comment]
I have the same issue.

Here is where the `SheetRoute` starts to animate.

https://github.com/jamesblasco/modal_bottom_sheet/blob/e44458d2359565324e117bb3d41da04f5e60362e/sheet/lib/src/route/sheet_route.dart#L375-L381

It seems while animation is happening and another `ScrollView` is subscribes to `SheetController` it breaks it.

https://github.com/jamesblasco/modal_bottom_sheet/blob/e44458d2359565324e117bb3d41da04f5e60362e/sheet/lib/src/sheet.dart#L329-L344

**Comment by maRci002** [comment]
I am lost but it seems the `SheetPrimaryScrollController` is recreted every time when layout happens

https://github.com/jamesblasco/modal_bottom_sheet/blob/e44458d2359565324e117bb3d41da04f5e60362e/sheet/lib/src/sheet.dart#L421-L422

I think the workaround will be a `Timer` inside my `Bloc` and when it expires it makes my `ScrollView` `primary: true` ...
