### ISSUE TITLE
Cannot build on Flutter Channel Beta & Master 3.7.0 (soon to be Stable) - ModalBottomSheetRoute imported from material as well

### ISSUE THREAD

**Issue by mariopepe** [jamesblasco/modal_bottom_sheet#311]
Cannot build any project using `modal_bottom_sheet` and Flutter on channel Beta and Master.
**Channel Beta is going to be brought to stable on the 25th of January, so in 9 days.**

```
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/
modal_bottom_sheet-2.1.2/lib/src/material_with_modal_page_route.dart:4:1:
Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and
'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
```

**Comment by dany2709** [comment]
I have the same problem
Version: beta

`../../AppData/Local/Pub/Cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/bar_bottom_sheet.dart:102:13: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/bar_bottom_sheet.dart:125:10: Error: A value of type 'Object?' can't be returned from an async function with return type 'Future<T?>'.
 - 'Object' is from 'dart:core'.
 - 'Future' is from 'dart:async'.
  return result;
         ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:28:13: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:50:10: Error: A value of type 'Object?' can't be returned from an async function with return type 'Future<T?>'.
 - 'Object' is from 'dart:core'.
 - 'Future' is from 'dart:async'.
  return result;
         ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/material_with_modal_page_route.dart:4:1: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
import '../modal_bottom_sheet.dart';
`

**Comment by eli1stark** [comment]
I made a [fork](https://github.com/eli1stark/modal_bottom_sheet) with fixes until the official fix will be available. Use at your own risk. You can reference it in your `pubspec.yaml` like so:
 ```
  modal_bottom_sheet:
    git:
      url: https://github.com/eli1stark/modal_bottom_sheet.git
      ref: main
 ```

**Comment by raulmabe-labhouse** [comment]
Same issue here

**Comment by saulrmzlpz** [comment]
Same issue.

**Comment by mark8044** [comment]
This is confusing, does this mean showModalBottomSheet is now a part of flutter material?  If so, what do we do about the ios13 Cupertino style widget

In the meantime @eli1stark fork does work 👍  but what are the long term prospects here?   The Cupertino one you've build is outstanding...

**Comment by OrgilTs** [comment]
same issue 

Failed to build iOS app
Error (Xcode): ../../../../../.pub-cache/hosted/pub.dev/firebase_core-1.24.0/lib/src/firebase_app.dart:18:25: Error: Member not found: 'FirebaseAppPlatform.verifyExtends'.


Could not build the application for the simulator.
Error launching application on iPhone 14.


Help me please

**Comment by AlexDochioiu** [comment]
> I made a [fork](https://github.com/eli1stark/modal_bottom_sheet) with fixes until the official fix will be available. Use at your own risk. You can reference it in your `pubspec.yaml` like so:
> 
> ```
>  modal_bottom_sheet:
>    git:
>      url: https://github.com/eli1stark/modal_bottom_sheet.git
>      ref: main
>      path: modal_bottom_sheet
> ```

For anyone using this: highly recommend to use the actual commit instead of the branch to avoid potential future/unwanted changes:

```yaml
modal_bottom_sheet:
  git:
    url: https://github.com/eli1stark/modal_bottom_sheet.git
    ref: 2b3f9f84f46418c1b337968c88883995f65f47e7
    path: modal_bottom_sheet
```

**Comment by jamesblasco** [comment]
Please follow the migration guide I just created here https://github.com/jamesblasco/modal_bottom_sheet/issues/325
