### ISSUE TITLE
Cannot build on Flutter 3.7.0 (Stable)

### ISSUE THREAD

**Issue by cyberkaidev** [jamesblasco/modal_bottom_sheet#314]
: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
../…/src/material_with_modal_page_route.dart:4
import '../modal_bottom_sheet.dart';
^^^^^^^^^^^^^^^^^^^^^

: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
../…/bottom_sheets/material_bottom_sheet.dart:28
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^
: Error: A value of type 'Object?' can't be returned from an async function with return type 'Future<T?>'.
../…/bottom_sheets/material_bottom_sheet.dart:50
 - 'Object' is from 'dart:core'.

 - 'Future' is from 'dart:async'.
  return result;
         ^

: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
../…/bottom_sheets/bar_bottom_sheet.dart:102
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^
: Error: A value of type 'Object?' can't be returned from an async function with return type 'Future<T?>'.
../…/bottom_sheets/bar_bottom_sheet.dart:125
 - 'Object' is from 'dart:core'.
 - 'Future' is from 'dart:async'.
  return result;
         ^

Failed to compile application.

**Comment by samnbd** [comment]
same here

**Comment by ridwan-aswan** [comment]
same here

**Comment by devon** [comment]
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import '../modal_bottom_sheet.dart';
// import 'bottom_sheet_route.dart';
```

**Comment by AlmogAttal** [comment]
same thing here

**Comment by ashish-d-hh** [comment]
same here

**Comment by danReynolds** [comment]
Made a quick fix: https://github.com/jamesblasco/modal_bottom_sheet/pull/315

**Comment by followthemoney1** [comment]
+1 https://github.com/jamesblasco/modal_bottom_sheet/pull/316

**Comment by ashish-d-hh** [comment]
Please merge as soon as possible.

**Comment by petodavid** [comment]
When can we expect the new version?

**Comment by WiRight** [comment]
same here

**Comment by nashaf007** [comment]
same here

**Comment by BrahimAkar** [comment]
same here +1

**Comment by jamesblasco** [comment]
Wow thanks for everyone fixing the issues so fast! I do not have access to my laptop right now! I will push the fix @danReynolds later today as soon as I can. 🙏🏻

**Comment by dmitry-bdg** [comment]
same here +1

**Comment by devahmedghanim** [comment]
same here +1

**Comment by ps9310** [comment]
same here +1

**Comment by avive** [comment]
same here +1

**Comment by daveshirman** [comment]
@jamesblasco Thanks very much for this - is there any timeline on when this is gonna be pushed to pub.dev?

**Comment by jamesblasco** [comment]
Please follow the migration guide I just created here https://github.com/jamesblasco/modal_bottom_sheet/issues/325
