### ISSUE TITLE
Ballistic Animation was updated in Flutter 3.7.0 and breaks both packages

### ISSUE THREAD

**Issue by webhaikal** [jamesblasco/modal_bottom_sheet#317]
Referencing flutter/flutter#107735

This change introduces the `shouldIgnorePointer` variable to `BallisticScrollActivity` and breaks when building both packages when building as it now requires 4 params instead of 3. I have temporarily fixed the problem with my own fork by just assigning that variable to false, however I am not sure what the true value should be.

**Comment by JohannSchramm** [comment]
Same issue here.
Did some more research regarding if the value should be `true` or `false`, and this PR ([flutter/flutter#106890](https://github.com/flutter/flutter/pull/106890)) originally introduced the `shouldIgnorePointer` paramter. Previously the `shouldIgnorePointer` property of `BallisticScrollActivity` was a getter which returned the default value of `true`.

**Comment by jamesblasco** [comment]
Please follow the migration guide I just created here https://github.com/jamesblasco/modal_bottom_sheet/issues/325

**Comment by jamesblasco** [comment]
Please follow the migration guide I just created here https://github.com/jamesblasco/modal_bottom_sheet/issues/325
