### ISSUE TITLE
Please provide an example on how to use this library without routes

### ISSUE THREAD

**Issue by andrasferenczi** [jamesblasco/modal_bottom_sheet#32]
I would like to use this library by skipping the `show__Sheet` method and rendering the modal directly.

I understand that `ModalBottomSheet` documentation says it is 'rarely used directly', but can it be?

So far I have tried returning simply with a `ModalBottomSheet`, but nothing appears on the screen.

Before spending more time on this, I though I would ask if this is even possible and if so, is there an example somewhere for it?

Thank you

**Comment by jamesblasco** [comment]
That part of the documentation was copied from the `BottomSheet` original widget from the Flutter framework. 
I didn't build it for other uses in mind more than using it as a ModalRoute.

Despite that, you can give it a try. What controls the modal position is the animation controller. The modal is hidden by default, so you should pass an animation controller parameter and animate it forward.

**Comment by andrasferenczi** [comment]
Thank you for the quick reply, it looks like it's working. Will play around with it a bit.

One minor feedback would be to add some comment to the `expanded` parameter on the `ModalBottomSheet`, as I thought that would determine if the bottom sheet is visible or not.

**Comment by jamesblasco** [comment]
Thanks, I added the description. You can check the status of the ModalBottomSheet right now with the AnimationController.value. Should improve that tough
