### ISSUE TITLE
Error: 'ModalBottomSheetRoute' is imported from both

### ISSUE THREAD

**Issue by Umesh-Kumar** [jamesblasco/modal_bottom_sheet#320]
Issue details:
/AppData/Local/Pub/Cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:28:13: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^

**Comment by jemuri** [comment]
issue too

**Comment by jamesblasco** [comment]
Please follow the migration guide I just created here https://github.com/jamesblasco/modal_bottom_sheet/issues/325

**Comment by harshitAmar** [comment]
I've fixed it for me and here it is, You can use it by writing
modal_bottom_sheet:
    git:
      url: https://github.com/harshitAmar/modal_bottom_sheet.git
      ref: main
