### ISSUE TITLE
Unexpected behavior of the bottom sheet with nested scrollables

### ISSUE THREAD

**Issue by ishmelev23** [jamesblasco/modal_bottom_sheet#33]
**Problem:**
If you put nested scrollables inside the bottom sheet, then the scroll controller will handle scroll notifications from both of it.
It leads to unexpected behavior f.e. when you have a parent vertical scrollable and put a horizontal scrollable in it.
In this way, if you scroll the horizontal scrollable to the start then the sheet will handle scroll notifications, start tracking your gestures and try to close the sheet.

**Solution description:**
According to [Flutter Docs](https://api.flutter.dev/flutter/widgets/ScrollNotification-class.html), it may be fixed very easily (I hope) by adding one line of code.
> Notifications bubble up through the tree, which means a given NotificationListener will receive notifications for all descendant Scrollable widgets. To focus on notifications from the nearest Scrollable descendant, check that the depth property of the notification is zero.

**Solution:**
So you can just add [here](https://github.com/jamesblasco/modal_bottom_sheet/blob/master/lib/src/bottom_sheet.dart#L245) `notification.depth==0` to handle notification only from the top scrollable widget.

**Comment by jamesblasco** [comment]
Thankss, I will try it and add it in the new update if it works
