### ISSUE TITLE
Unexpected shadow at the top of modal sheet

### ISSUE THREAD

**Issue by davis33321** [jamesblasco/modal_bottom_sheet#34]
Hello guys,

When my modal sheet pops up, there is some unexpected shadow at the top. I tried "elevation: 0" but it doesn't work. Any one could shed some light on dealing with this? Thanks a lot!

![image](https://user-images.githubusercontent.com/18228204/86527038-7c3a7380-becd-11ea-827a-e7f1524b741f.png)

**Comment by jamesblasco** [comment]
Could you share some code?

**Comment by davis33321** [comment]
Thanks @jamesblasco 

So everything starts with main.dart where i use MaterialWithModalsPageRoute to build the HomePage() Widget.

> `void main() {`
> `  runApp(MaterialApp(`
> `    title: "",`
> `    onGenerateRoute: (settings) {`
> `          return MaterialWithModalsPageRoute(`
> `              builder: (context) => HomePage(),`
> `              settings: settings);`
> `    },`
> `  ));`
> `}`

Inside HomePage.dart, I use PageView() and bottomNavigationBar to do the tab navigation.

> `Widget build(BuildContext context) {`
> `    return Scaffold(`
> `      bottomNavigationBar: Footer(index: getPageIndex, onTapFunction: onTapChangePage),`
> `      body: PageView(`
> `        children: <Widget>[`
> `          PageOne(),`
> `          PageTwo()`
> `        ],`
> `        controller: pageController,`
> `        onPageChanged: whenPageChanges,`
> `        physics: NeverScrollableScrollPhysics(),`
> `      ),`
> `    );`
> `  }`

In PageOne.dart, i have a FloatingActionButton and it will call showCupertinoModalBottomSheet once it is pressed.

> `Widget build(BuildContext context) {`
> `    return Scaffold(`
> `      appBar: Header(),`
>   `    body: Item(name: "Hello", brand: "Taylor"),`
>    `   floatingActionButton: FloatingActionButton(`
>     `    elevation: 0,`
>       `  mini: true,`
>         `backgroundColor: Colors.orange,`
>         `child: Icon(Icons.add),`
> `        onPressed: () {`
> 
>    `       showCupertinoModalBottomSheet(`
>     `        elevation: 0,`
>       `      isDismissible: true,`
>       `      expand: true,`
>         `    context: context,`
>          `   backgroundColor: Colors.transparent,`
>            ` builder: (context, scrollController) =>`
>              `   SearchReference(`
>               `    scrollController: scrollController,`
>                 `  isAddingReference: true,`
>                ` ),`
> `          );`
> `},`
>   `    ),`
>   `  );`
>  ` }`


Sorry that the code may be a bit messy, let me know if there is anything unclear. Thank you!

**Comment by jamesblasco** [comment]
So you set the modal to have a transparent background no? Are you using a BackdropFilter inside the modal?

**Comment by davis33321** [comment]
Thanks @jamesblasco. 

I solved this problem, it's because I used  `backgroundColor:  Colors.transparent` in CupertinoNavigationBar. It seems the navigation bar will automatically produce a blurring effect to the content behind it. So, i just changed it to sth like Colors.white to solve the problem~

**Comment by jamesblasco** [comment]
Glad you solved it. I think it is because some examples have this backgroundColor set to transparent without not reason. I will remove it.  Thank you for pointing that out
