### ISSUE TITLE
Bottom Sheet loses data on move

### ISSUE THREAD

**Issue by drosa88** [jamesblasco/modal_bottom_sheet#35]
I tried the Bottom sheet with a simple increment integer with a + icon. If I change the state with incrementing a number and I move the bottom sheet, for example sliding a bit down and up, then the new state is lost. It shows me the initial number.

Is this normal that event to close the dialog is fired on moving the sheet? Or is there an error in my code?

By the way: Thanks for your great work!

**Comment by jamesblasco** [comment]
If you saw my some of the code, maybe be I can help. It should keep the state inside, but maybe there us a bug

**Comment by drosa88** [comment]
Here´s my code:

Parent Class:

`class MinistryReportHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
        navigationBar: CupertinoNavigationBar(
          middle: Text("Juni 2020",
              style: Theme.of(context).appBarTheme.textTheme.headline1),
          backgroundColor: Theme.of(context).primaryColor,
        ),
        child: CupertinoScaffold(
          body: new Builder(
            builder: (context) => new Container(
                child: Column(children: [
              HomeSummary(),
              FloatingActionButton(
                  child: Icon(Icons.add),
                  backgroundColor: Theme.of(context).primaryColor,
                  onPressed: () =>
                      CupertinoScaffold.showCupertinoModalBottomSheet(
                          duration: Duration(milliseconds: 350),
                          bounce: true,
                          context: context,
                          builder: (context, scrollController) =>
                              AddReportDataDialog(scrollController))),
            ])),
          ),
        ));
  }
}`

Main Class:

`class AddReportDataDialog extends StatelessWidget {
  final ScrollController scrollController;

  AddReportDataDialog(this.scrollController);

  @override
  Widget build(BuildContext context) {
    return CupertinoScaffold(
      body: Center(
        child: HomeReportList(scrollController),
      ),
    );
  }
}
`

Bottom Sheet Class:

`class HomeReportList extends StatelessWidget {
  final ScrollController scrollController;

  HomeReportList(this.scrollController);

  final List<Report> report = [
    Report(minutes: 0, placements: 0, returnVisits: 0, studies: 0, videos: 0)
  ];

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Padding(
        padding: const EdgeInsets.only(top: 15),
        child: CupertinoScaffold(
          body: ListView(
            physics: ClampingScrollPhysics(),
            controller: scrollController,
            children: <Widget>[
              Container(
                  margin:
                      EdgeInsets.only(left: 15, right: 15, bottom: 25, top: 20),
                  child: Text("Daten hinzufügen",
                      style: Theme.of(context)
                          .textTheme
                          .headline3
                          .copyWith(color: Colors.white))),
              AddReportDataTile(
                title: "Stunden",
                summary: 15,
              ),
              AddReportDataTile(
                title: "Abgaben",
                summary: 18,
              ),
              AddReportDataTile(
                title: "Rückbesuche",
                summary: 4,
              ),
              AddReportDataTile(
                title: "Studien",
                summary: 1,
              ),
              AddReportDataTile(
                title: "Videos",
                summary: 12,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
`

Thanks in advance! :)

**Comment by jamesblasco** [comment]
I think you are using StatefulWidget incorrectly. 
Widgets should be immutable (data inside can't be changed after created). What persists is the State.

This is one of the core principles of Flutter, you don't control when a widget is recreated, but you control the state of StatefulWidget.

Your params in the StatefulWidget should be always final :
```dart
class AddReportDataTile extends StatefulWidget {
 final  String title;
 final int summary;

  AddReportDataTile({this.title, this.summary});

  @override
  _AddReportDataTileState createState() => _AddReportDataTileState();
}
```
 And what you modify is the state:

```dart
class _AddReportDataTileState extends State<AddReportDataTile> {
   int summary;

   @override   
   void initState() {
       summary = widget.summary
   }

  void addSummary() {
    setState(() {
      summary++;
    });
  }

  void subtractSummary() {
    setState(() {
        summary--;
    });
  }

```

**Comment by drosa88** [comment]
Thanks for your help.

If I change the code like your instructions, the state is not changing anymore.

Current code:

```
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

class AddReportDataTile extends StatefulWidget {
  final String title;
  final int summary;

  AddReportDataTile({this.title, this.summary});

  @override
  _AddReportDataTileState createState() => _AddReportDataTileState();
}

class _AddReportDataTileState extends State<AddReportDataTile> {
  int summary;

  @override
  // ignore: must_call_super
  void initState() {
    summary = widget.summary;
  }

  void addSummary() {
    setState(() {
      summary++;
    });
  }

  void subtractSummary() {
    setState(() {
      summary--;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      color: Colors.white10,
      margin: EdgeInsets.only(left: 15, right: 15, bottom: 10),
      clipBehavior: Clip.antiAlias,
      elevation: .2,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(10.0),
      ),
      child: ListTile(
        leading: IconButton(
            icon: Icon(Icons.remove),
            color: Colors.white,
            visualDensity: VisualDensity.adaptivePlatformDensity,
            onPressed: subtractSummary),
        trailing: IconButton(
            color: Colors.white, icon: Icon(Icons.add), onPressed: addSummary),
        title: Column(
          children: <Widget>[
            Text(widget.title,
                textAlign: TextAlign.center,
                style: Theme.of(context)
                    .textTheme
                    .bodyText2
                    .copyWith(color: Colors.white)),
            Text(widget.summary.toString(),
                textAlign: TextAlign.center,
                style: Theme.of(context)
                    .textTheme
                    .bodyText1
                    .copyWith(color: Colors.white)),
          ],
        ),
        contentPadding: EdgeInsets.all(10),
      ),
    );
  }
}

```

**Comment by jamesblasco** [comment]
Change widget.summary.toString() inside text widget to ‘$summary’

**Comment by drosa88** [comment]
It works now, thanks :)

**Comment by jamesblasco** [comment]
Your welcome!
