### ISSUE TITLE
Why is my showCupertinoModalBottomSheet not zooming out?

### ISSUE THREAD

**Issue by Tristannos** [jamesblasco/modal_bottom_sheet#363]
Normally in IOS you have that zoom out effect when the bottom sheet is opend. 

For some reason i cannot find the reason why it is not working for me.

![SCR-20230817-j0t](https://github.com/jamesblasco/modal_bottom_sheet/assets/55278228/375dca40-2097-46cb-b24a-d44b50035015)
<img width="651" alt="SCR-20230817-j27" src="https://github.com/jamesblasco/modal_bottom_sheet/assets/55278228/c49dcc08-f5f6-4dce-8780-96ebb1c24cfb">

**Comment by SoMWbRa** [comment]
return CupertinoScaffold(
      body: Builder(builder: (cupertinoScaffoldContext) {
        return Scaffold(
          body: ... (
            // somewhere 
            onPressed: () {
                    CupertinoScaffold.showCupertinoModalBottomSheet(
                      context: cupertinoScaffoldContext,
                      builder: (context) => const MyOtherScreen(word: null),
                    );
                  },
          ),
        );
      }),
    );

**Comment by Tristannos** [comment]
Yes thankyou!!!

**Comment by Leekogram** [comment]
Gpd 

> ```
> return CupertinoScaffold(
>       body: Builder(builder: (cupertinoScaffoldContext) {
>         return Scaffold(
>           body: ... (
>             // somewhere 
>             onPressed: () {
>                  CupertinoScaffold.showCupertinoModalBottomSheet(
>                     context: cupertinoScaffoldContext,
>                     builder: (context) => const MyOtherScreen(),
>                  );
>               },
>           ),
>         );
>       }),
>     );
> ```

God bless you
