### ISSUE TITLE
[sheet] 1.0.0-pre scrollable.dart SheetState miss devicePixelRatio

### ISSUE THREAD

**Issue by GenLix** [jamesblasco/modal_bottom_sheet#364]
flutter version: 3.13.0

**Comment by ihadabs** [comment]
same

```
Failed to build iOS app
Error (Xcode):
../../../../../../../.pub-cache/hosted/pub.dev/sheet-1.0.0-pre/lib/src/scrollable.dar
t:313:7: Error: The non-abstract class 'SheetState' is missing implementations for
these members:


Encountered error while building for device.

flutter --version 
Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (2 days ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0
```

**Comment by saltedpotatos** [comment]
Ive opened PR #365 with changes that mirror the Flutter PR that introduced devicePixelRatio changes.

**Comment by Maatteogekko** [comment]
This should stay open until a new version with the fix is released, don't you think?

**Comment by gibahjoe** [comment]
> > @GenLix @Maatteogekko
> > You can use the following till it's fixed:
> > ```yaml
> > sheet:
> >     git:
> >         url: https://github.com/ihadabs/sheet.git
> > ```
> 
> Hi! Where should I add the code?

add it to pubspec
