### ISSUE TITLE
showDragHandle and topRadius for showCupertinoModalBottomSheet

### ISSUE THREAD

**Issue by Qpace-Team** [jamesblasco/modal_bottom_sheet#371]
Hey, 
why did you guys remove native showDragHandle and topRadius from your package? and topRadius from showCupertinoModalBottomSheet? These are highly usable for customization.

**Comment by jamesblasco** [comment]
You can create your own ModalBottomSheet that behaves like you want. The `CupertinoModalBottomSheet` tries to feel like the native iOS and they only provide a pre-defined style. While we could provide infinite customization options we would need to also need to mantain it, and our scope is limited
