### ISSUE TITLE
Is this project abandoned ?

### ISSUE THREAD

**Issue by nandakista** [jamesblasco/modal_bottom_sheet#382]
This is a very good and useful package. I use it on every projects.
But the last package update was 14 months ago, and version 3.0.0-pre hasn't launched yet.
So what is the status of this package, is the project still being maintained ??

**Comment by ziqq** [comment]
@jamesblasco, Can u answer this issue? Do u maintain this package or not?

**Comment by jamesblasco** [comment]
Hey! As you can already guess I have not been properly maintaining this package. My freetime has been quite limited this year to focus it on open source. I still plan to maintain this, or find someone that would be interested in helping me with that. 

I pushed a new version that supports the latest Flutter 3.19
https://pub.dev/packages/modal_bottom_sheet
