### ISSUE TITLE
The demo code version is not fit with README.

### ISSUE THREAD

**Issue by magic3584** [jamesblasco/modal_bottom_sheet#384]
Such as `showCupertinoModalBottomSheet` is deprecated in demo and I failed show modal using the function in 2.1.2

``` dart
showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      builder: (context) => DetailPage(),
    );
```

Any help?

**Comment by CyMathew** [comment]
Deprecated in which demo?

You will need `MaterialWithModalsPageRoute` on the route you're navigating from.

**Comment by magic3584** [comment]
The demo perhaps is in Example folder on master branch by then.
I don't know whether it works by now.

**Comment by jamesblasco** [comment]
Please see the example Cupertino Modal fit:
https://github.com/jamesblasco/modal_bottom_sheet/blob/e44458d2359565324e117bb3d41da04f5e60362e/modal_bottom_sheet/example/lib/main.dart#L166-L174
