### ISSUE TITLE
3.0.0-pre version is not compatible with  dart SDK 2.17 (flutter 3.0.1)

### ISSUE THREAD

**Issue by ICU2020** [jamesblasco/modal_bottom_sheet#385]
run "flutter pub get":

  
The current Flutter SDK version is 3.0.1.

Because sail depends on modal_bottom_sheet >=3.0.0-pre which requires Flutter SDK version >=3.7.0, version solving failed.

**Comment by ziqq** [comment]
Hello, @ICU2020 show your `flutter doctor -v`

I use Flutter 3.16.9 and Dart 3.2.6 this package work for me

**Comment by jamesblasco** [comment]
Hey, the new version should be able to work with latest Dart 3.3.0, Flutter 3.19
https://pub.dev/packages/modal_bottom_sheet
