### ISSUE TITLE
Error: The setter 'isMergedIntoParent' isn't defined for the class 'SemanticsNode' in flutter 3.19.0

### ISSUE THREAD

**Issue by LeoAiolia** [jamesblasco/modal_bottom_sheet#388]
- 'SemanticsNode' is from 'package:flutter/src/semantics/semantics.dart' ('../../../fvm/versions/3.19.0/packages/flutter/lib/src/semantics/semantics.dart').
[        ] Try correcting the name to the name of an existing setter, or defining a setter or field named 'isMergedIntoParent'.
[        ]       ..isMergedIntoParent = node.isPartOfNodeMerging

![图片](https://github.com/jamesblasco/modal_bottom_sheet/assets/16910025/c1c4e75d-214b-4cfa-8732-bab3e830abf7)

flutter version: 3.19.0

**Comment by OpenJarvisAI** [comment]
pub-cache/git/modal_bottom_sheet-d5c9ceb4e2263f63f449ed9b1c212a34c6dcaa5d/sheet/lib/src/scrollable.dart:871:9: Error: The setter 'isMergedIntoParent' isn't defined for the class 'SemanticsNode'.
 - 'SemanticsNode' is from 'package:flutter/src/semantics/semantics.dart' ('../../../../development/flutter/packages/flutter/lib/src/semantics/semantics.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'isMergedIntoParent'.
      ..isMergedIntoParent = node.isPartOfNodeMerging
        ^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

**Comment by jamesblasco** [comment]
Hey, this is fixed in the new release:
https://pub.dev/packages/modal_bottom_sheet

**Comment by LeoAiolia** [comment]
sheet：1.0.0  is ok
