### ISSUE TITLE
Not work anymore

### ISSUE THREAD

**Issue by OpenJarvisAI** [jamesblasco/modal_bottom_sheet#389]
pub-cache/git/modal_bottom_sheet-d5c9ceb4e2263f63f449ed9b1c212a34c6dcaa5d/sheet/lib/src/scrollable.dart:871:9: Error: The setter 'isMergedIntoParent' isn't defined for the class 'SemanticsNode'.
 - 'SemanticsNode' is from 'package:flutter/src/semantics/semantics.dart' ('../../../../development/flutter/packages/flutter/lib/src/semantics/semantics.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'isMergedIntoParent'.
      ..isMergedIntoParent = node.isPartOfNodeMerging
        ^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

**Comment by daih27** [comment]
Check this PR: https://github.com/jamesblasco/modal_bottom_sheet/pull/387#issuecomment-1973587447

This fixed it for me.

**Comment by jamesblasco** [comment]
Hey, this is fixed in the new release:
https://pub.dev/packages/modal_bottom_sheet
