### ISSUE TITLE
ScrollController not attached to any scroll views.

### ISSUE THREAD

**Issue by allanwolski** [jamesblasco/modal_bottom_sheet#42]
I'm getting an error after upgrading to version 0.2.0

```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 110 pos 12: '_positions.isNotEmpty'

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:110:12)
#3      _ModalBottomSheetState._handleScrollUpdate (package:modal_bottom_sheet/src/bottom_sheet.dart:261:46)
#4      _ModalBottomSheetState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:modal_bottom_sheet/src/bottom_sheet.dart:376:27)
#5      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:129:41)
#6      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:47:20)
...
```

**Comment by bierbaumtim** [comment]
Hey @allanwolski 
Thanks for reporting this issue.
I will look at that later this day.

**Comment by jamesblasco** [comment]
@bierbaumtim thanks!! After merging the pull request it looks we use the scrollController before checking if it has clients

**Comment by SonPham17** [comment]
I also encountered the same error. I use ListView in Material Modal.
I fixed it by the following:
ListView(
                controller: scrollController,
                scrollDirection: Axis.horizontal,
                children: <Widget>[],
)

showMaterialModalBottomSheet(
              expand: false,
              duration: Duration(milliseconds: 500),
              context: context,
              builder: (context, scrollController) => _buildBottomSheet(scrollController),
);

**Comment by jamesblasco** [comment]
It is fixed on master, publishing new version soon
