### ISSUE TITLE
Package sheet modal sheet is squared on 3.24.0

### ISSUE THREAD

**Issue by virskor** [jamesblasco/modal_bottom_sheet#420]
import 'package:sheet/route.dart';

```dart
  pageBuilder: (BuildContext context, GoRouterState state) {
            return MaterialExtendedPage<void>(
              key: state.pageKey,
              child: const Home(),
            );
          },
```

```dart
 pageBuilder: (BuildContext context, GoRouterState state) =>
          CupertinoSheetPage<void>(
        key: state.pageKey,
        child: const SettingsDelegate(),
      ),
```

![Xnip2024-08-08_16-15-06](https://github.com/user-attachments/assets/b16a5f40-72c9-409e-9770-8ce5716a4ee2)

it's squared on 3.24.0 stable channel

**Comment by habibasseiss** [comment]
The reason is an issue with `ClipRRect` and `ColorFiltered` in 3.24.0. Seems to be solved in the master channel, so let's wait for a new version release. Source: https://github.com/flutter/flutter/issues/153118

**Comment by virskor** [comment]
This bug has been fixed in 3.24.1, closed

**Comment by qiqetes** [comment]
#153118 found this

**Comment by qiqetes** [comment]
I found this issue in 3.24.3 #153118
