### ISSUE TITLE
How to properly dismiss the modal & how to make edges of CupertinoModalBottomSheet more round

### ISSUE THREAD

**Issue by agnesjang98** [jamesblasco/modal_bottom_sheet#46]
Hi, I tried to dismiss the modal with a button press within the modal (#24) by calling `Navigator.of(context).pop()` but when I do, the modal shows an animation of going back to a previous screen within the modal (a plain blank modal) instead of being dismissed. It then shows this error in my console: 
`flutter: Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3803 pos 12: '_history.isNotEmpty': is not true.`
I'm using `showCupertinoModalBottomSheet` to be able to have navigation within the modal.

In addition, when I call `showCupertinoModalBottomSheet` I'm also supplying the shape parameter.

```        showCupertinoModalBottomSheet(
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(50)),
              ...
 ```
No matter what value I put in `BorderRadius.circular()`, the radius of the edges of my modal stays the same. Any insight would be appreciated!

**Comment by jamesblasco** [comment]
About your first issue I would need more code to see the problem. Are you using a Navigator or a CupertinoTabView widget inside the modal. It looks like you have one, try to remove it if you don't need it. Otherwise, you will have to get the other Navigator with a GlobalKey.

Related to the second issue, my apologies, shape is not used in showCupertinoModalBottomSheet, I will remove it in the next version. You can change the radius with the topRadius param

**Comment by agnesjang98** [comment]
I'm using a Navigator. Here is part of my code if you can help me debug:
```
    return Container(
        child: Material(
            child: Navigator(
          onGenerateRoute: (_) => MaterialPageRoute(
            builder: (context) => Builder(
              builder: (context) => CupertinoPageScaffold(
                ...
                                children: <Widget>[
                                  GestureDetector(
                                    child: Container(
                                        ...
                                    onTap: () {
                                      // HERE: attempts to dismiss modal
                                      Navigator.pop(context);
                                    },
                                  ),
                                  GestureDetector(
                                    child: Container(
                                    ...
                                    onTap: () {
                                     // I have a button here that pushes to the next screen within my modal
                                      Navigator.of(context).push(
                                          MaterialPageRoute(
                                              builder: (context) =>
                                                  CupertinoPageScaffold(
                                                      navigationBar:
                                                          CupertinoNavigationBar(
                                                              ...
```

Here is my code for calling showCupertinoModalBottomSheet:
```
              showCupertinoModalBottomSheet(
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(25)),
                context: context,
                builder: (context, scrollController) {
                // AddContact is the returned widget in the code above
                  return AddContact(
                    ...
                  );
                },
              ).then((value) {
                Navigator.pop(context);
              });
```

**Comment by jamesblasco** [comment]
I commented here the ways I think are the most appropriate to access the Navigator that pushes the modal when there are nested Navigators.  #49
