### ISSUE TITLE
Consider making WebFrame its own package?

### ISSUE THREAD

**Issue by MisterJimson** [jamesblasco/modal_bottom_sheet#5]
Your web demo is very nice: https://jamesblasco.github.io/modal_bottom_sheet/#/

Looks very clean, device frame is well aligned, content is perfectly inside. Maybe worth it to be its own library?

In the future could add configurations for different devices, etc.

**Comment by jamesblasco** [comment]
Thanks @MisterJimson!

Check this package, is awesome [device_preview](https://pub.dev/packages/device_preview).
I was  going to propose there a new widget with just the frame or  build myself a widget on top of the package.
I think it is better than building everything again from scratch

**Comment by MisterJimson** [comment]
Yeah DevicePreview seems pretty nice. It has some issues running on web but I was able to work around them.

**Comment by MisterJimson** [comment]
Looks like Tim agrees :) https://twitter.com/timsneath/status/1249021681865093121

**Comment by jamesblasco** [comment]
@MisterJimson Hope this helps, I will try to add more devices in the future

https://github.com/jamesblasco/flutter_showcase

**Comment by MisterJimson** [comment]
Dude that is sick. Nice work.
