### ISSUE TITLE
Floating modal, why no gap at the bottom

### ISSUE THREAD

**Issue by jasonlaw** [jamesblasco/modal_bottom_sheet#51]
Hi,

I follow exactly the example code for the floating modal, however, there is different that my one does not have a gap at the bottom, may I know what am I missing?

My example:
![image](https://user-images.githubusercontent.com/107820/87890597-d27cea00-ca69-11ea-9c12-c0159db9b6e9.png)

Package example:
![image](https://user-images.githubusercontent.com/107820/87890624-e6285080-ca69-11ea-82d1-50d128e43a3f.png)

**Comment by jamesblasco** [comment]
I only added the safe area padding, you can set an extra bottom padding
