### ISSUE TITLE
Scrolling ListView inside Modal Presentation is not smooth

### ISSUE THREAD

**Issue by basilmariano** [jamesblasco/modal_bottom_sheet#52]
![Screen Shot 2020-07-22 at 2 59 48 PM](https://user-images.githubusercontent.com/5466582/88144749-ff78fa80-cc2b-11ea-8fa4-a0ed201e84cf.png)

**Comment by jamesblasco** [comment]
Thanks for the screenshot, could you write a bit more what is not performant?

I the simulator it doesn't look like there is a list view, are you using debug or profile mode?

**Comment by jamesblasco** [comment]
There were some problems that made the inside widget rebuild multiple times. That part should be fixed. Let's reopen this issue if the problems persists with the newer versions
