### ISSUE TITLE
Webview not scrolling inside the modal

### ISSUE THREAD

**Issue by rbocobo** [jamesblasco/modal_bottom_sheet#53]
Webviews do not scroll inside the modal

`showModalBottomSheet(
                                            context: context,
                                            builder: (builder) {
                                              return new Container(
                                                height: MediaQuery.of(context).size.height / 4,
                                                child: new Container(
                                                  decoration: new BoxDecoration(color: Colors.amber, borderRadius: new BorderRadius.only(topLeft: const Radius.circular(20.0), topRight: const Radius.circular(20.0))),
                                                  child: Container(
                                                      child: WebView(
                                                        initialUrl: 'https://google.com',
                                                      )),
                                                ),
                                              );
                                            },
                                          );`

**Comment by jamesblasco** [comment]
See https://stackoverflow.com/a/62276169/8096916
