### ISSUE TITLE
Rebuild

### ISSUE THREAD

**Issue by AugustToko** [jamesblasco/modal_bottom_sheet#56]
When sliding the sheet, it will always cause reconstruction,
In some cases this can cause performance issues 😢

**Comment by jamesblasco** [comment]
Working on that.
This PR will solve it 
https://github.com/jamesblasco/modal_bottom_sheet/pull/55

**Comment by jamesblasco** [comment]
This is now on master and will be published in next version

**Comment by robvr** [comment]
> This is now on master and will be published in next version

Any date for the new version? Very much appreciated
