### ISSUE TITLE
How to add Padding?

### ISSUE THREAD

**Issue by pro100svitlo** [jamesblasco/modal_bottom_sheet#58]
Hello!

Can you please tell me how Padding can be applied for the whole bottomSheetDialog?
For example, I need to add padding from left/right and make it transparent from the sides.

thanks!

**Comment by jamesblasco** [comment]
You should use containerWidget param.
Check the floatingModalBottomSheet example for that:
https://github.com/jamesblasco/modal_bottom_sheet/blob/master/example/lib/modals/floating_modal.dart
