### ISSUE TITLE
Could I call some method for closing the modal?

### ISSUE THREAD

**Issue by Hong-Cho** [jamesblasco/modal_bottom_sheet#59]
I call showMaterialModalBottomSheet. There are radio group buttons. I want to close the modal sheet when radio is tabbed. Is there any method for closing manually? Sometimes people need to close the sheet by calling function. Looking forward to your answer.

**Comment by jamesblasco** [comment]
It is a normal route, so you can close it by calling Navigator.of(context).pop().
