### ISSUE TITLE
ScrollController not attached to any scroll views

### ISSUE THREAD

**Issue by siemarell** [jamesblasco/modal_bottom_sheet#6]
Hi. First of all, thank you for this awesome library.
I've encountered an issue. When I ignore `scrollController`, which is passed as the second argument in `build` function, and my page uses any widget with its own scroll controller. I get this exception: 
`VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 110 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.`

Here is the code:
```dart
import 'package:flutter/material.dart';
import 'package:modal_bottom_sheet/modal_bottom_sheet.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      onGenerateRoute: (settings) {
        return MaterialWithModalsPageRoute(builder: (_) => MyHomePage());
      },
      initialRoute: '/',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      // home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Title'),
      ),
      body: Center(child: Container()),
      floatingActionButton: FloatingActionButton(
        onPressed: () => showCupertinoModalBottomSheet(
            context: context,
            builder: (context, _) => Scaffold(
                  body: Center(
                    child: TextField(),
                  ),
                )),
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), 
    );
  }
}
```
[Here](https://github.com/siemarell/scroll_view_bug_example) is example repo 
Steps to reproduce:
1. Run the app
2. Click on the floating action button to open modal view
3. Click on the text input

As far as I can understand, every scroll controller has to be attached to some widget. When we focus on text input, all scroll controllers are triggered, even the one, passed via build function. It is not attached, so I get an error.
As a workaround, I've created a dummy widget and attach the controller to it.
In my opinion, this should be done internally in the library

**Comment by jamesblasco** [comment]
Thank you for the feedback and the detailed explanation.
I will take a look to it this weekend.

**Comment by bierbaumtim** [comment]
I think the issue is, that at Line 2 in _handleScrollUpdate in bottom_sheet.dart the check _scrollController.hasClients is missing.

**Comment by bierbaumtim** [comment]
@siemarell You're not completly right. ScrollControllers need to be attached, when you want so read values or call methods on it. So if you have a ScrollController which theoreticly can't be attached you need to check if the scrollController hasClients. If it returns true you can work with this scrollController otherwise you had to attach it first.

Looking in methods like jumpTo, show that they include an assertion which also checks hasClients.
