### ISSUE TITLE
show the modal with 70% of the width

### ISSUE THREAD

**Issue by rdonoso** [jamesblasco/modal_bottom_sheet#63]
Hello, how are you? i would like to know if there is a possibility to show the modal with an specific width proporcional of the screen device, now is using by default the full widht of the screen.

**Comment by jamesblasco** [comment]
You can create you own modal with your own constraints.

Check this example that adds a padding to the modal
https://github.com/jamesblasco/modal_bottom_sheet/blob/master/example/lib/modals/floating_modal.dart

**Comment by rdonoso** [comment]
Thanks James, i will give it a try!
