### ISSUE TITLE
Compile error after importing the library

### ISSUE THREAD

**Issue by kristijorgji** [jamesblasco/modal_bottom_sheet#64]
After installing the library and trying out the example simple show alert code, the code does not compile.
I get the following error

`Compiler message:
../../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheet.dart:184:3: Error: Type 'ParametricCurve' not found.
  ParametricCurve<double> animationCurve;
  ^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheet.dart:184:3: Error: Expected 0 type arguments.
  ParametricCurve<double> animationCurve;
  ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheet.dart:318:3: Error: Type 'ParametricCurve' not found.
  ParametricCurve<double> get _defaultCurve =>
  ^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheet.dart:318:3: Error: Expected 0 type arguments.
  ParametricCurve<double> get _defaultCurve =>
  ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/utils/bottom_sheet_suspended_curve.dart:28:41: Error: Type 'ParametricCurve' not found.
class BottomSheetSuspendedCurve extends ParametricCurve<double> {
                                        ^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/utils/bottom_sheet_suspended_curve.dart:28:41: Error: Expected 0 type arguments.
class BottomSheetSuspendedCurve extends ParametricCurve<double> {
                                        ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheet.dart:184:3: Error: 'ParametricCurve' isn't a type.
  ParametricCurve<double> animationCurve;
  ^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheet_route.dart:42:27: Error: Getter not found: 'linux'.
      case TargetPlatform.linux:
                          ^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheet_route.dart:43:27: Error: Getter not found: 'macOS'.
      case TargetPlatform.macOS:
                          ^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheet_route.dart:44:27: Error: Getter not found: 'windows'.
      case TargetPlatform.windows:
                          ^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 8.
`

This is how I am using it:

showCupertinoModalBottomSheet(
                    context: context,
                    builder: (context, scrollController) => MySuperPage(),
                  );

**Comment by kristijorgji** [comment]
Also using one example from the repo still gives the same error, cannot compile

`    showCupertinoModalBottomSheet(
                    expand: true,
                    isDismissible: false,
                    context: context,
                    backgroundColor: Colors.transparent,
                    builder: (context, scrollController) =>
                        ModalInsideModal(
                            scrollController: scrollController,
                            reverse: false),
                  );`

**Comment by jamesblasco** [comment]
What flutter version are you using? This is expected to work with lastest 1.20 stable release.
If you want to use a previous Flutter version you should try an older version of the package

**Comment by thecherrie** [comment]
Having the exact same issue.

**Comment by thecherrie** [comment]
Switching to a previous version did fix it.

**Comment by kristijorgji** [comment]
> What flutter version are you using? This is expected to work with lastest 1.20 stable release.
> If you want to use a previous Flutter version you should try an older version of the package

I have an old version actually 

v1.12.13+hotfix.9
--


Is any version of this library for my version of flutter ?

I tried to upgrade but many other things broke, that is reason also why we did not upgrade yet actually. Lot of things break, pod complains in ios anything breaks on flutter upgrade...

**Comment by jamesblasco** [comment]
Everything before August 5th should work for you.

There are some breaking changes with Flutter 1.20 but definitely it is worth the update.
