### ISSUE TITLE
Question: Possible to remove background of new modal?

### ISSUE THREAD

**Issue by proformance** [jamesblasco/modal_bottom_sheet#68]
Hi,

Great stuff!

Is it possible to set the background of the new modal to complete transparency? I'm planning to use the barrierColor to make the whole background a little greyed out instead.

(CustomAdd() contains a top padding)

Right now I'm using `modal_bottom_sheet 0.2.0+1` from https://pub.dev/packages/modal_bottom_sheet

<img width="443" alt="Screenshot 2020-09-09 at 14 55 42" src="https://user-images.githubusercontent.com/18383533/92601399-0aa3ea80-f2ad-11ea-947c-14a962e19382.png">

```
  CupertinoScaffold.showCupertinoModalBottomSheet(
    expand: true,
    context: context,
    backgroundColor: Colors.transparent,
    builder: (context, scrollController) => Material(
      child: CustomAdd(),
      color: Colors.transparent,
    ),
  );
```

Best regards

**Comment by jamesblasco** [comment]
Do you need cupertinoModalBottomSheet for that?

mm I think that is a shadow that appears here 

https://github.com/jamesblasco/modal_bottom_sheet/blob/54b926a36c6ab8321d814d98f63cd8f888f2e9dd/lib/src/bottom_sheets/cupertino_bottom_sheet.dart#L45.

You can try to create a custom containerBuilder, like the class `_CupertinoBottomSheetContainer`

**Comment by proformance** [comment]
Thanks, that solves my problem!
