### ISSUE TITLE
showBarModalBottomSheet's isDismissible set to true but still I am able to dismiss with finger gesture

### ISSUE THREAD

**Issue by ShanjinurIslam** [jamesblasco/modal_bottom_sheet#76]
showBarModalBottomSheet(
        context: context,
        isDismissible: false,
        useRootNavigator: true,
        builder: (context, scrollController) => Container(
          height: MediaQuery.of(context).size.height * .3,
        ),
);

I am doing a loading screen in bottom modal and I want it to dismiss when the task is complete. So I set isDismissible to false to manually dismiss when my task is complete. but in my code I am able to dismiss. is there any fix for this?

**Comment by jamesblasco** [comment]
Hello.
isDismissible is used to not allow to dismiss the modal by touching to the barrier.

If you don't want to allow the user to close the modal by dragging it you can use the param enableDrag: false.

Also for a better UX, you should allow them to close the modal. You can use WillPopScope to display an alert to the user if he is trying to close the modal, so he can save or cancel the task.

**Comment by ShanjinurIslam** [comment]
Thanks a lot! I spent 30 mins finding how to do that and then gave up :-(,
