### ISSUE TITLE
Error: VelocityTracker - Too many positional arguments: 0 allowed, but 1 found.

### ISSUE THREAD

**Issue by jpraus** [jamesblasco/modal_bottom_sheet#78]
Hi, I would love to use your library but I keep getting the following error, seems like your library is incompatible with the latest Flutter package?

> /C:/Flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.1+1-dev/lib/src/bottom_sheet.dart:303:43: Error: Too many positional arguments: 0 allowed, but 1 found.
> Try removing the extra positional arguments.
>         _velocityTracker = VelocityTracker(pointerKind);
>                                           ^
> /C:/Flutter/packages/flutter/lib/src/gestures/velocity_tracker.dart:150:7: Context: The class 'VelocityTracker' has a constructor that takes no arguments.
> class VelocityTracker {

Using flutter 1.20.3

**Comment by NoahVersace** [comment]
this has already been fixed.
try to pub get the newest version 🤙🏾

**Comment by jamesblasco** [comment]
https://github.com/jamesblasco/modal_bottom_sheet/issues/69
