### ISSUE TITLE
I used the code correctly, but when it runs to the real machine, it reports an error, as follows:

### ISSUE THREAD

**Issue by sliverRing** [jamesblasco/modal_bottom_sheet#79]
`Xcode's output:
↳
Pods-Runner-eytxkdbkjsqutchhkimtteayvcml
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/modal_bottom_sheet-0.2.1+1-dev/lib/src/bottom_sheet.dart:303:43: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
        _velocityTracker = VelocityTracker(pointerKind);
                                          ^
../../flutter/packages/flutter/lib/src/gestures/velocity_tracker.dart:150:7: Context: The class 'VelocityTracker' has a constructor that takes no arguments.
`

**Comment by jamesblasco** [comment]
Please use 
modal_bottom_sheet: 0.2.0 
in your pubspec

I published a version 0.2.1+1-dev with breaking changes related to Flutter 1.22
https://github.com/jamesblasco/modal_bottom_sheet/issues/78
