### ISSUE TITLE
open and close modal programmatically

### ISSUE THREAD

**Issue by wrtisans** [jamesblasco/modal_bottom_sheet#80]
thanks for your package, i love it ... i would like to ask if is there a way to open and close the modals programmatically ... for example if i need to use showCupertinoModalBottomSheet to show login form if no auth user exists ... thanks for your help ... i know this is not a bug of this package but i've searched and tried a lot of ways but i cant make it work 

i've seen that this is possible using GetX but im not sure ...

**Comment by jamesblasco** [comment]
Programatically you open a modal by calling
showCupertinoModalBottomSheet,

To close it you can call Navigator.of(context).pop() inside the modal.

Check the official api from Flutter as they are very similar

https://api.flutter.dev/flutter/material/showModalBottomSheet.html
