### ISSUE TITLE
Error Too few positional arguments: 1 required, 0 given

### ISSUE THREAD

**Issue by jheimesilveirazup** [jamesblasco/modal_bottom_sheet#83]
i am getting the following error when trying to use

Launching lib\main.dart on sdk gphone x86 arm in debug mode...
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.2/lib/src/bottom_sheet.dart:303:43: Error: Too few positional arguments: 1 required, 0 given.
        _velocityTracker = VelocityTracker();
                                          ^
/C:/flutter/packages/flutter/lib/src/gestures/velocity_tracker.dart:152:3: Context: Found this candidate, but the arguments don't match.
  VelocityTracker(this.kind);
  ^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by dopecoder** [comment]
+1

**Comment by jamesblasco** [comment]
Flutter version?

**Comment by jamesblasco** [comment]
See https://github.com/jamesblasco/modal_bottom_sheet/issues/69

**Comment by jheimesilveirazup** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.22.0-12.1.pre, on Microsoft Windows [versÃ£o
    10.0.19041.508], locale pt-BR)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor 
      --android-licenses
[√] Chrome - develop for the web    
[√] Android Studio (version 4.0)    
[√] VS Code (version 1.49.2)        
[√] Connected device (5 available)  

! Doctor found issues in 1 category.
