### ISSUE TITLE
UI elements within Modal not rebuilding when state is changed

### ISSUE THREAD

**Issue by FickleLife** [jamesblasco/modal_bottom_sheet#84]
I have a modal which displays a `ListView` and has `RadioListTiles` within. When I select a `RadioListTile`, the state data changes but the UI won't rebuild until the modal is closed and re opened. I have also noticed when changing the elements within the modal will not hot update when you save the source.dart file - you need to close and re open the modal. 

Any ideas how to get widgets within the modal to rebuild when state is changed?

**Comment by bierbaumtim** [comment]
Could you please provide a small example to reproduce the issue.

And which flutter version you use?

**Comment by FickleLife** [comment]
```
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (13 days ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```

Thanks, I'll put some code in a repo in a few hours

**Comment by FickleLife** [comment]
Looks like it's my code at fault - apologies, I'll close this one.

**Comment by ayaanpathan** [comment]
I'm facing the same issue. Can anyone help me with this?

**Comment by ItsRyanWu** [comment]
> Looks like it's my code at fault - apologies, I'll close this one.

How did you get round this issue?

**Comment by ayaanpathan** [comment]
> > Looks like it's my code at fault - apologies, I'll close this one.
> 
> How did you get round this issue?

I used a stateful widget

**Comment by ItsRyanWu** [comment]
> > > Looks like it's my code at fault - apologies, I'll close this one.
> > 
> > 
> > How did you get round this issue?
> 
> I used a stateful widget

I'm already using stateful widget inside of modal
But I just found a solution here: https://stackoverflow.com/questions/52414629/how-to-update-state-of-a-modalbottomsheet-in-flutter, look at the second answer which is suggest use Flutter's StatefulBuilder to wrap ModalBottomSheet
