### ISSUE TITLE
simple import of the  the package does not work

### ISSUE THREAD

**Issue by leadpresence** [jamesblasco/modal_bottom_sheet#85]
Poor documentation of using this package:
Do we need to import all these?

import 'modals/floating_modal.dart';
import 'modals/modal_complex_all.dart';
import 'modals/modal_fit.dart';
import 'modals/modal_inside_modal.dart';
import 'modals/modal_will_scope.dart';
import 'modals/modal_with_navigator.dart';
import 'modals/modal_with_nested_scroll.dart';
import 'modals/modal_with_scroll.dart';
import 'modals/modal_with_page_view.dart';

**Comment by jamesblasco** [comment]
You just need to import the package as another flutter package;

`import 'package:modal_bottom_sheet/modal_bottom_sheet.dart';`

Here you have the installation guide 
https://pub.dev/packages/modal_bottom_sheet/install

And here the explanations and functions that call them
https://pub.dev/packages/modal_bottom_sheet

Both `showCupertinoModalBottomSheet` and `showMaterialModalBottomSheet` are heavily inspired in the Flutter implementation `showModalBottomSheet` that you can read here https://api.flutter.dev/flutter/material/showModalBottomSheet.html

Those are just examples of widgets used with the modal package.
