### ISSUE TITLE
Child container rebuild to much when i drag down to dismiss

### ISSUE THREAD

**Issue by kekedaine** [jamesblasco/modal_bottom_sheet#91]
Child container rebuild to much when i drag down to dismiss. 
... and i can't reslove this issue
Thank u so much.

![dainv 2020-10-17 at 12 24 04](https://user-images.githubusercontent.com/4715657/96329081-c6f28c80-1073-11eb-9e83-377ab50bb492.JPG)

**Comment by welfvh** [comment]
Same here. Especially when used with a Firebase Storage image, this is really ugly.

**Comment by jamesblasco** [comment]
It has been solved on the master branch. The code from the screenshot needs to use the version from master that hasn’t been published yet

**Comment by robvr** [comment]
When will the code from master be published? Thx
