### ISSUE TITLE
Example needs updation

### ISSUE THREAD

**Issue by sunnykinger** [jamesblasco/modal_bottom_sheet#92]
The example breaks and I am not able to understand the issue. 
The best way you check is to use 
`modal_bottom_sheet: ^0.2.2` as a dependency in your example project instead of a relative path, and issues will start to show up.

**Comment by jamesblasco** [comment]
The code in master is not released yet as a dependency. To run the example use the git code as dependency:

modal_bottom_sheet: 
   git:  https://github.com/jamesblasco/modal_bottom_sheet/
