### ISSUE TITLE
Weird scroll behaviour when modal closing on iOS

### ISSUE THREAD

**Issue by sooxt98** [jamesblasco/modal_bottom_sheet#94]
iOS gives weird scroll behaviour without `NeverScrollableScrollPhysics` , the list should freeze when closing the modal

![scroll_bug](https://user-images.githubusercontent.com/13378059/97263733-8f979300-185e-11eb-8b11-c80a3d4a00ee.gif)

**Comment by jamesblasco** [comment]
You can use ClampingScrollPhysics for now

**Comment by jamesblasco** [comment]
Duplicate: https://github.com/jamesblasco/modal_bottom_sheet/issues/47

**Comment by sooxt98** [comment]
@jamesblasco this shouldn't be close, it's should work with default scroll behaviours, the native one doesn't behave like the clamp one
